using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Utility;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration.Internal;

[Generator]
internal class InternalPySpecialNamesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var declarationsProvider = Utils.CreateNamedTypeSymbolProvider(context, "PySharp.Runtime.PySpecialNames");

        context.RegisterSourceOutput(declarationsProvider, static (ctx, symbol) =>
        {
            var fields = symbol.GetMembers().OfType<IFieldSymbol>().Where(f => f.IsConst && f.Type.SpecialType == SpecialType.System_String);

            var builder = new IndentedStringBuilder()
                .AppendAutoGeneratedTag()
                .EnableNullable()
                .UsingNamespace("System.Collections.Generic")
                .AppendLine()
                .AppendLine("namespace PySharp.Runtime;")
                .AppendLine()
                .AppendLine("partial class PySpecialNames")
                .EnterBlock()
                    .AppendLine("internal static partial IEnumerable<string> EnumerateNonGeneratedNames()")
                    .EnterBlock()
                        .ForEach(fields, static (builder, field) =>
                        {
                            builder.AppendLine($"yield return {field.Name};");
                        })
                    .ExitBlock()
                .ExitBlock();

            ctx.AddSource($"{symbol.Name}.NonGenerated.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        });
    }
}
