using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Utility;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration.Internal;

partial class InternalPyTypeObjectGenerator
{
    private static void GenerateSlotsFile(
        SourceProductionContext ctx,
        List<IMethodSymbol> directMethods,
        List<IGrouping<string, IMethodSymbol>> slotsMemberGroups,
        Dictionary<string, (IFieldSymbol field, INamedTypeSymbol type)> slotsMemberFieldTypes)
    {
        var builder = new IndentedStringBuilder()
            .AppendAutoGeneratedTag()
            .EnableNullable()
            .UsingNamespace("System.Collections.Generic")
            .UsingNamespace("PySharp.Runtime.Calls")
            .UsingNamespace("PySharp.Runtime.Calls.Extensions")
            .AppendLine()
            .AppendLine("namespace PySharp.Modules.Builtins;")
            .AppendLine()
            .AppendLine("partial class PyTypeObject")
            .EnterBlock()
                .AppendLine("protected internal sealed partial class PyTypeSlots")
                .EnterBlock();

        // Delegate fields for methods without SlotsMember
        foreach (var method in directMethods)
        {
            var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == PySharpTypes.PySpecialMethodAttributeName);
            var delegateType = attributeData.GetConstructorArgument<INamedTypeSymbol>(1);
            if (delegateType is null) continue;
            builder.AppendLine($"internal {delegateType.Name}? {method.Name};");
        }

        // Nested types for each SlotsMember group — generate delegate fields inside the field's type
        foreach (var group in slotsMemberGroups)
        {
            if (!slotsMemberFieldTypes.TryGetValue(group.Key, out var info)) continue;

            var nestedType = info.type;
            builder.AppendLine();
            builder.AppendLine($"internal sealed partial class {nestedType.Name}");
            builder.EnterBlock();

            foreach (var method in group)
            {
                var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == PySharpTypes.PySpecialMethodAttributeName);
                var delegateType = attributeData.GetConstructorArgument<INamedTypeSymbol>(1);
                if (delegateType is null) continue;
                builder.AppendLine($"internal {delegateType.Name}? {method.Name};");
            }

            builder.ExitBlock();
        }

        // Forwarding accessors for SlotsMember methods — exposes nested type's fields directly on PyTypeSlots
        foreach (var group in slotsMemberGroups)
        {
            if (!slotsMemberFieldTypes.TryGetValue(group.Key, out var info)) continue;
            var fieldName = group.Key;
            foreach (var method in group)
            {
                var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == PySharpTypes.PySpecialMethodAttributeName);
                var delegateType = attributeData.GetConstructorArgument<INamedTypeSymbol>(1);
                if (delegateType is null) continue;
                builder.AppendLine($"internal {delegateType.Name}? {method.Name} => {fieldName}?.{method.Name};");
            }
        }

        builder
            .AppendLine()
            .AppendLine("internal void FillNullWith(PyTypeSlots other)")
            .EnterBlock();

        // FillNullWith: direct fields
        foreach (var method in directMethods)
        {
            builder.AppendLine($"{method.Name} ??= other.{method.Name};");
        }

        // FillNullWith: nested type fields
        foreach (var group in slotsMemberGroups)
        {
            if (!slotsMemberFieldTypes.TryGetValue(group.Key, out var info)) continue;
            var fieldName = group.Key;
            builder.AppendLine($"if (other.{fieldName} != null)");
            builder.EnterBlock();
            builder.AppendLine($"{fieldName} ??= new {info.type.Name}();");
            foreach (var method in group)
            {
                builder.AppendLine($"{fieldName}.{method.Name} ??= other.{fieldName}.{method.Name};");
            }
            builder.ExitBlock();
        }

        builder
            .ExitBlock()
            .AppendLine()
            .AppendLine("internal void TrySetSlot(string name, PyObject value)")
            .EnterBlock()
                .AppendLine("switch (name)")
                .EnterBlock()
                    .AppendLine("case \"__new__\": New = value.ToClsArgsKwargsFunction(); break;");

        // TrySetSlot: direct fields
        foreach (var method in directMethods)
        {
            var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == PySharpTypes.PySpecialMethodAttributeName);
            var specialName = attributeData.GetConstructorArgument<string>(0);
            var delegateType = attributeData.GetConstructorArgument<INamedTypeSymbol>(1);
            if (specialName is null || delegateType is null) continue;
            var extMethod = GetSlotConverterMethodName(specialName, delegateType.Name);
            builder.AppendLine($"case \"{specialName}\": {method.Name} = value.{extMethod}(); break;");
        }

        // TrySetSlot: nested type fields
        foreach (var group in slotsMemberGroups)
        {
            if (!slotsMemberFieldTypes.TryGetValue(group.Key, out var info)) continue;
            var fieldName = group.Key;
            foreach (var method in group)
            {
                var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == PySharpTypes.PySpecialMethodAttributeName);
                var specialName = attributeData.GetConstructorArgument<string>(0);
                var delegateType = attributeData.GetConstructorArgument<INamedTypeSymbol>(1);
                if (specialName is null || delegateType is null) continue;
                var extMethod = GetSlotConverterMethodName(specialName, delegateType.Name);
                builder.AppendLine($"case \"{specialName}\": {fieldName} ??= new(); {fieldName}.{method.Name} = value.{extMethod}(); break;");
            }
        }

        // every slot dunder name, "__new__" included (declared manually on the
        // slots class); probed by the runtime re-resolution machinery
        var allSlotNames = new List<string> { "__new__" };
        foreach (var method in directMethods)
        {
            var specialName = method.GetAttributes().First(a => a.AttributeClass?.Name == PySharpTypes.PySpecialMethodAttributeName)
                .GetConstructorArgument<string>(0);
            if (specialName is not null)
                allSlotNames.Add(specialName);
        }
        foreach (var group in slotsMemberGroups)
        {
            foreach (var method in group)
            {
                var specialName = method.GetAttributes().First(a => a.AttributeClass?.Name == PySharpTypes.PySpecialMethodAttributeName)
                    .GetConstructorArgument<string>(0);
                if (specialName is not null)
                    allSlotNames.Add(specialName);
            }
        }

        static (string? specialName, string? delegateType) ReadSlotDef(IMethodSymbol method)
        {
            var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == PySharpTypes.PySpecialMethodAttributeName);
            return (attributeData.GetConstructorArgument<string>(0), attributeData.GetConstructorArgument<INamedTypeSymbol>(1)?.Name);
        }

        builder
            .ExitBlock()   // switch (name)
            .ExitBlock()   // TrySetSlot
            .AppendLine()
            .AppendLine("internal static readonly string[] AllSlotNames =")
            .AppendLine("[")
            .Indent()
            .ForEach(allSlotNames, static (builder, name) => builder.AppendLine($"\"{name}\","))
            .Dedent()
            .AppendLine("];")
            .AppendLine()
            .AppendLine("private static readonly HashSet<string> SlotNameSet = new(AllSlotNames);")
            .AppendLine()
            .AppendLine("internal static bool IsSlotName(string name) => SlotNameSet.Contains(name);")
            .AppendLine()
            .AppendLine("internal void ClearSlot(string name)")
            .EnterBlock()
                .AppendLine("switch (name)")
                .EnterBlock()
                    .AppendLine("case \"__new__\": New = null; break;")
                    .ForEach(directMethods, static (builder, method) =>
                    {
                        var (specialName, _) = ReadSlotDef(method);
                        if (specialName is null) return;
                        builder.AppendLine($"case \"{specialName}\": {method.Name} = null; break;");
                    })
                    .ForEach(slotsMemberGroups, static (builder, group) =>
                    {
                        foreach (var method in group)
                        {
                            var (specialName, _) = ReadSlotDef(method);
                            if (specialName is null) continue;
                            builder.AppendLine($"case \"{specialName}\": if ({group.Key} is not null) {group.Key}.{method.Name} = null; break;");
                        }
                    })
                .ExitBlock()
            .ExitBlock()
            .AppendLine()
            .AppendLine("// CPython update_one_slot's specific test: a wrapper descriptor wraps the")
            .AppendLine("// provider's exact slot delegate (FillSlot shares the instance between the")
            .AppendLine("// slot field and the type dict), so the wrapped delegate is wired directly")
            .AppendLine("// instead of a closure calling through the wrapper.")
            .AppendLine("internal bool TrySetWrappedSlot(string name, PyWrapperDescriptorObject wrapper)")
            .EnterBlock()
                .AppendLine("switch (name)")
                .EnterBlock()
                    .AppendLine("case \"__new__\": return false;")
                    .ForEach(directMethods, static (builder, method) =>
                    {
                        var (specialName, delegateType) = ReadSlotDef(method);
                        if (specialName is null || delegateType is null) return;
                        builder.AppendLine($"case \"{specialName}\": {{ if (wrapper._func is {delegateType} f) {{ {method.Name} = f; return true; }} return false; }}");
                    })
                    .ForEach(slotsMemberGroups, static (builder, group) =>
                    {
                        foreach (var method in group)
                        {
                            var (specialName, delegateType) = ReadSlotDef(method);
                            if (specialName is null || delegateType is null) continue;
                            builder.AppendLine($"case \"{specialName}\": {{ if (wrapper._func is {delegateType} f) {{ {group.Key} ??= new(); {group.Key}.{method.Name} = f; return true; }} return false; }}");
                        }
                    })
                    .AppendLine("default: return false;")
                .ExitBlock()
            .ExitBlock()
            .ExitBlock()
            .ExitBlock();

        ctx.AddSource("PyTypeObject.Slots.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
