using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration.Internal;

[Generator]
public class InternalPyTypeObjectGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var declarationsProvider = Utils.CreateNamedTypeSymbolProvider(context, "PySharp.Modules.Builtins.PyTypeObject.Declarations");

        context.RegisterSourceOutput(declarationsProvider, static (ctx, symbol) =>
        {
            var methods = symbol.GetMembers().OfType<IMethodSymbol>().Where(m => m.IsPartialDefinition);

            var builder = new IndentedStringBuilder()
                .AppendAutoGeneratedTag()
                .EnableNullable()
                .UsingNamespace("PySharp.Runtime.Calls")
                .UsingNamespace("System.Collections.Generic")
                .UsingNamespace("System.Diagnostics")
                .AppendLine()
                .AppendLine("namespace PySharp.Modules.Builtins;")
                .AppendLine()
                .AppendLine("partial class PyTypeObject")
                .EnterBlock()
                    .ForEach(methods, static (builder, method) =>
                    {
                        var parameters = string.Join(", ", method.Parameters.Select(p =>
                        {
                            string typeStr = p.Type.Name == "TObject" ? "PyObject" : p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            return $"{typeStr} {p.Name}";
                        }));

                        builder
                            .AppendLine($"private protected virtual PyResult {method.Name}({parameters})")
                            .EnterBlock()
                            .AppendLine("throw new UnreachableException(\"Implemented by PyTypeObject<TObject>\");")
                            .ExitBlock()
                            .AppendLine();
                    })
                .ExitBlock();

            ctx.AddSource("PyTypeObject.Virtual.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));

            var builder2 = new IndentedStringBuilder()
                .AppendAutoGeneratedTag()
                .EnableNullable()
                .UsingNamespace("PySharp.Runtime")
                .UsingNamespace("PySharp.Runtime.Calls")
                .UsingNamespace("System.Collections.Generic")
                .AppendLine()
                .AppendLine("namespace PySharp.Modules.Builtins;")
                .AppendLine()
                .AppendLine("partial class PyTypeObject<TObject>")
                .EnterBlock()
                    .ForEach(methods, static (builder, method) =>
                    {
                        var parametersDef = string.Join(", ", method.Parameters.Select(p =>
                        {
                            string typeStr = p.Type.Name == "TObject" ? "PyObject" : p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            return $"{typeStr} {p.Name}";
                        }));

                        var parametersCall = string.Join(", ", method.Parameters.Select(p =>
                        {
                            return p.Name == "self" ? "selfOfT" : p.Name;
                        }));

                        builder
                            .AppendLine($"private protected sealed override PyResult {method.Name}({parametersDef})")
                            .EnterBlock()
                            .AppendLine($"if (self is not TObject selfOfT)")
                            .Indent()
                            .AppendLine($"return PyResult.TypeError(PySR.Runtime_Type_MethodReceiveSelfWithWrongType, PySpecialNames.{method.Name}, FullName, self.PyType.FullName);")
                            .Dedent()
                            .AppendLine($"return {method.Name}({parametersCall});")
                            .ExitBlock()
                            .AppendLine();
                    })
                .ExitBlock();

            ctx.AddSource("PyTypeObjectOfT.Sealed.g.cs", SourceText.From(builder2.ToString(), Encoding.UTF8));

            var methodsList = methods.ToList();

            // Pre-compute SlotsMember info for each method
            static string? GetSlotsMemberName(IMethodSymbol method)
            {
                var attr = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                if (attr == null) return null;
                foreach (var kvp in attr.NamedArguments)
                    if (kvp.Key == "SlotsMember" && kvp.Value.Value is string sm)
                        return sm;
                return null;
            }

            var methodSlotsMember = methodsList.ToDictionary(
                m => m,
                m => GetSlotsMemberName(m), SymbolEqualityComparer.Default);

            // Find PyTypeSlots to resolve field types for SlotsMember groups
            var pyTypeSlotsSymbol = symbol.ContainingType.GetTypeMembers("PyTypeSlots").FirstOrDefault();

            // Group methods by SlotsMember
            var directMethods = methodsList.Where(m => methodSlotsMember[m] == null).ToList();
            var slotsMemberGroups = methodsList
                .Where(m => methodSlotsMember[m] != null)
                .GroupBy(m => methodSlotsMember[m]!)
                .ToList();

            // Resolve field and its type for each SlotsMember value
            var slotsMemberFieldTypes = new Dictionary<string, (IFieldSymbol field, INamedTypeSymbol type)>(StringComparer.Ordinal);
            foreach (var group in slotsMemberGroups)
            {
                var fieldName = group.Key;
                var field = pyTypeSlotsSymbol?.GetMembers(fieldName).OfType<IFieldSymbol>().FirstOrDefault();
                if (field?.Type is INamedTypeSymbol namedType)
                    slotsMemberFieldTypes[fieldName] = (field, namedType);
            }

            // Helper: get extension method name from delegate type name
            static string GetExtensionMethodName(string delegateName)
                => delegateName.StartsWith("Py") ? "To" + delegateName.Substring(2) : "To" + delegateName;

            var builder3 = new IndentedStringBuilder()
                .AppendAutoGeneratedTag()
                .EnableNullable()
                .UsingNamespace("PySharp.Runtime.Calls")
                .UsingNamespace("PySharp.Runtime.Calls.Extensions")
                .AppendLine()
                .AppendLine("namespace PySharp.Modules.Builtins;")
                .AppendLine()
                .AppendLine("partial class PyTypeObject")
                .EnterBlock()
                    .AppendLine("protected internal sealed partial class PyTypeSlots")
                    .EnterBlock();

            // Delegate fields for methods without SlotsMember
            foreach (var method in directMethods)
            {
                var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                var delegateType = (INamedTypeSymbol)attributeData.ConstructorArguments[1].Value!;
                builder3.AppendLine($"internal {delegateType.Name}? {method.Name};");
            }

            // Nested types for each SlotsMember group — generate delegate fields inside the field's type
            foreach (var group in slotsMemberGroups)
            {
                if (!slotsMemberFieldTypes.TryGetValue(group.Key, out var info)) continue;

                var nestedType = info.type;
                builder3.AppendLine();
                builder3.AppendLine($"internal sealed partial class {nestedType.Name}");
                builder3.EnterBlock();

                foreach (var method in group)
                {
                    var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                    var delegateType = (INamedTypeSymbol)attributeData.ConstructorArguments[1].Value!;
                    builder3.AppendLine($"internal {delegateType.Name}? {method.Name};");
                }

                builder3.ExitBlock();
            }

            // Forwarding accessors for SlotsMember methods — exposes nested type's fields directly on PyTypeSlots
            foreach (var group in slotsMemberGroups)
            {
                if (!slotsMemberFieldTypes.TryGetValue(group.Key, out var info)) continue;
                var fieldName = group.Key;
                foreach (var method in group)
                {
                    var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                    var delegateType = (INamedTypeSymbol)attributeData.ConstructorArguments[1].Value!;
                    builder3.AppendLine($"internal {delegateType.Name}? {method.Name} => {fieldName}?.{method.Name};");
                }
            }

            builder3
                .AppendLine()
                .AppendLine("internal PyTypeSlots Clone()")
                .EnterBlock()
                    .AppendLine("return (PyTypeSlots)MemberwiseClone();")
                .ExitBlock()
                .AppendLine()
                .AppendLine("internal void FillNullWith(PyTypeSlots other)")
                .EnterBlock();

            // FillNullWith: direct fields
            foreach (var method in directMethods)
            {
                builder3.AppendLine($"{method.Name} ??= other.{method.Name};");
            }

            // FillNullWith: nested type fields
            foreach (var group in slotsMemberGroups)
            {
                if (!slotsMemberFieldTypes.TryGetValue(group.Key, out var info)) continue;
                var fieldName = group.Key;
                builder3.AppendLine($"if (other.{fieldName} != null)");
                builder3.EnterBlock();
                builder3.AppendLine($"{fieldName} ??= new {info.type.Name}();");
                foreach (var method in group)
                {
                    builder3.AppendLine($"{fieldName}.{method.Name} ??= other.{fieldName}.{method.Name};");
                }
                builder3.ExitBlock();
            }

            builder3
                .ExitBlock()
                .AppendLine()
                .AppendLine("internal void TrySetSlot(string name, PyObject value)")
                .EnterBlock()
                    .AppendLine("switch (name)")
                    .EnterBlock()
                        .AppendLine("case \"__new__\": New = value.ToClsArgsKwargsFunction(); break;");

            // TrySetSlot: direct fields
            foreach (var method in directMethods)
            {
                var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                var specialName = (string)attributeData.ConstructorArguments[0].Value!;
                var delegateType = (INamedTypeSymbol)attributeData.ConstructorArguments[1].Value!;
                var extMethod = GetExtensionMethodName(delegateType.Name);
                builder3.AppendLine($"case \"{specialName}\": {method.Name} = value.{extMethod}(); break;");
            }

            // TrySetSlot: nested type fields
            foreach (var group in slotsMemberGroups)
            {
                if (!slotsMemberFieldTypes.TryGetValue(group.Key, out var info)) continue;
                var fieldName = group.Key;
                foreach (var method in group)
                {
                    var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                    var specialName = (string)attributeData.ConstructorArguments[0].Value!;
                    var delegateType = (INamedTypeSymbol)attributeData.ConstructorArguments[1].Value!;
                    var extMethod = GetExtensionMethodName(delegateType.Name);
                    builder3.AppendLine($"case \"{specialName}\": {fieldName} ??= new(); {fieldName}.{method.Name} = value.{extMethod}(); break;");
                }
            }

            builder3
                            .ExitBlock()
                        .ExitBlock()
                    .ExitBlock()
                .ExitBlock();

            ctx.AddSource("PyTypeObject.Slots.g.cs", SourceText.From(builder3.ToString(), Encoding.UTF8));

            var builder4 = new IndentedStringBuilder()
                .AppendAutoGeneratedTag()
                .EnableNullable()
                .UsingNamespace("PySharp.Modules.Builtins")
                .AppendLine("namespace PySharp.Runtime;")
                .AppendLine()
                .AppendLine("partial class PySpecialNames")
                .EnterBlock()
                    .ForEach(methods, static (builder, method) =>
                    {
                        var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                        var specialName = (string)attributeData.ConstructorArguments[0].Value!;
                        builder.AppendLine($"public const string {method.Name} = \"{specialName}\";");
                    })
                    .AppendLine()
                    .AppendLine("partial class Interned")
                    .EnterBlock()
                        .ForEach(methods, static (builder, method) =>
                        {
                            builder.AppendLine($"public static readonly PyStrObject {method.Name} = PyStrObject.InternPool.FromString(PySpecialNames.{method.Name});");
                        })
                    .ExitBlock()
                    .AppendLine()
                    .AppendLine("internal static partial System.Collections.Generic.IEnumerable<string> EnumerateGeneratedNames()")
                    .EnterBlock()
                        .ForEach(methods, static (builder, method) =>
                        {
                            builder.AppendLine($"yield return {method.Name};");
                        })
                    .ExitBlock()
                .ExitBlock();

            ctx.AddSource("PySpecialNames.g.cs", SourceText.From(builder4.ToString(), Encoding.UTF8));
            
            var builder5 = new IndentedStringBuilder()
                .AppendAutoGeneratedTag()
                .EnableNullable()
                .UsingNamespace("PySharp.Runtime")
                .UsingNamespace("PySharp.Runtime.Calls")
                .UsingNamespace("PySharp.Runtime.PyAttributes")
                .UsingNamespace("System.Collections.Generic")
                .AppendLine()
                .AppendLine("namespace PySharp.Modules.Builtins;")
                .AppendLine()
                .AppendLine("partial class PyTypeObject<TObject>")
                .EnterBlock()
                    .ForEach(methods, static (builder, method) =>
                    {
                        var parameters = string.Join(", ", method.Parameters.Select(p =>
                        {
                            string typeStr = p.Type.Name == "TObject" ? "TObject" : p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            return $"{typeStr} {p.Name}";
                        }));

                        builder
                            .AppendLine($"protected virtual partial PyResult {method.Name}({parameters});")
                            .AppendLine();
                    })
                .ExitBlock();

            ctx.AddSource("PyTypeObjectOfT.Partial.g.cs", SourceText.From(builder5.ToString(), Encoding.UTF8));

        });
    }
}
