using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Utility;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration.Internal;

[Generator]
public class InternalPyTypeObjectGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var declarationsProvider = Utils.CreateNamedTypeSymbolProvider(context, "PySharp.Modules.Builtins.PyTypeObject.Declarations");

        context.RegisterSourceOutput(declarationsProvider, static (ctx, symbol) =>
        {
            var methods = symbol.GetMembers().OfType<IMethodSymbol>().Where(m => m.IsPartialDefinition);

            var builder = new IndentedStringBuilder()
                .AppendAutoGeneratedTag()
                .EnableNullable()
                .UsingNamespace("PySharp.Runtime.Calls")
                .UsingNamespace("System.Collections.Generic")
                .UsingNamespace("System.Diagnostics")
                .AppendLine()
                .AppendLine("namespace PySharp.Modules.Builtins;")
                .AppendLine()
                .AppendLine("partial class PyTypeObject")
                .EnterBlock()
                    .ForEach(methods, static (builder, method) =>
                    {
                        var parameters = string.Join(", ", method.Parameters.Select(p =>
                        {
                            string typeStr = p.Type.Name == "TObject" ? "PyObject" : p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            return $"{typeStr} {p.Name}";
                        }));

                        builder
                            .AppendLine($"private protected virtual PyResult {method.Name}({parameters})")
                            .EnterBlock()
                            .AppendLine("throw new UnreachableException(\"Implemented by PyTypeObject<TObject>\");")
                            .ExitBlock()
                            .AppendLine();
                    })
                .ExitBlock();

            ctx.AddSource("PyTypeObject.Virtual.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));

            var builder2 = new IndentedStringBuilder()
                .AppendAutoGeneratedTag()
                .EnableNullable()
                .UsingNamespace("PySharp.Runtime")
                .UsingNamespace("PySharp.Runtime.Calls")
                .UsingNamespace("System.Collections.Generic")
                .AppendLine()
                .AppendLine("namespace PySharp.Modules.Builtins;")
                .AppendLine()
                .AppendLine("partial class PyTypeObject<TObject>")
                .EnterBlock()
                    .ForEach(methods, static (builder, method) =>
                    {
                        var parametersDef = string.Join(", ", method.Parameters.Select(p =>
                        {
                            string typeStr = p.Type.Name == "TObject" ? "PyObject" : p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            return $"{typeStr} {p.Name}";
                        }));

                        var parametersCall = string.Join(", ", method.Parameters.Select(p =>
                        {
                            return p.Name == "self" ? "selfOfT" : p.Name;
                        }));

                        builder
                            .AppendLine($"private protected sealed override PyResult {method.Name}({parametersDef})")
                            .EnterBlock()
                            .AppendLine($"if (self is not TObject selfOfT)")
                            .Indent()
                            .AppendLine($"return PyResult.TypeError(PySR.Runtime_Type_MethodReceiveSelfWithWrongType, PySpecialNames.{method.Name}, FullName, self.PyType.FullName);")
                            .Dedent()
                            .AppendLine($"return {method.Name}({parametersCall});")
                            .ExitBlock()
                            .AppendLine();
                    })
                .ExitBlock();

            ctx.AddSource("PyTypeObjectOfT.Sealed.g.cs", SourceText.From(builder2.ToString(), Encoding.UTF8));

            var builder3 = new IndentedStringBuilder()
                .AppendAutoGeneratedTag()
                .EnableNullable()
                .UsingNamespace("PySharp.Runtime.Calls")
                .UsingNamespace("PySharp.Runtime.Calls.Extensions")
                .AppendLine()
                .AppendLine("namespace PySharp.Modules.Builtins;")
                .AppendLine()
                .AppendLine("partial class PyTypeObject")
                .EnterBlock()
                    .AppendLine("protected internal sealed partial class PyTypeSlots")
                    .EnterBlock()
                        .ForEach(methods, static (builder, method) =>
                        {
                            var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                            var delegateType = (INamedTypeSymbol)attributeData.ConstructorArguments[1].Value!;
                            builder.AppendLine($"internal {delegateType.Name}? {method.Name};");
                        })
                        .AppendLine()
                        .AppendLine("internal PyTypeSlots Clone()")
                        .EnterBlock()
                            .AppendLine("return (PyTypeSlots)MemberwiseClone();")
                        .ExitBlock()
                        .AppendLine()
                        .AppendLine("internal void FillNullWith(PyTypeSlots other)")
                        .EnterBlock()
                            .ForEach(methods, static (builder, method) =>
                            {
                                builder.AppendLine($"{method.Name} ??= other.{method.Name};");
                            })
                        .ExitBlock()
                        .AppendLine()
                        .AppendLine("internal void TrySetSlot(string name, PyObject value)")
                        .EnterBlock()
                            .AppendLine("switch (name)")
                            .EnterBlock()
                                .AppendLine("case \"__new__\": New = value.ToClsArgsKwargsFunction(); break;")
                                .ForEach(methods, static (builder, method) =>
                                {
                                    var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                                    var specialName = (string)attributeData.ConstructorArguments[0].Value!;
                                    var delegateType = (INamedTypeSymbol)attributeData.ConstructorArguments[1].Value!;
                                    string delegateName = delegateType.Name;
                                    string extMethod = delegateName.StartsWith("Py") ? "To" + delegateName.Substring(2) : "To" + delegateName;
                                    builder.AppendLine($"case \"{specialName}\": {method.Name} = value.{extMethod}(); break;");
                                })
                            .ExitBlock()
                        .ExitBlock()
                    .ExitBlock()
                .ExitBlock();

            ctx.AddSource("PyTypeObject.Slots.g.cs", SourceText.From(builder3.ToString(), Encoding.UTF8));

            var builder4 = new IndentedStringBuilder()
                .AppendAutoGeneratedTag()
                .EnableNullable()
                .UsingNamespace("PySharp.Modules.Builtins")
                .AppendLine("namespace PySharp.Runtime;")
                .AppendLine()
                .AppendLine("partial class PySpecialNames")
                .EnterBlock()
                    .ForEach(methods, static (builder, method) =>
                    {
                        var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                        var specialName = (string)attributeData.ConstructorArguments[0].Value!;
                        builder.AppendLine($"public const string {method.Name} = \"{specialName}\";");
                    })
                    .AppendLine()
                    .AppendLine("partial class Interned")
                    .EnterBlock()
                        .ForEach(methods, static (builder, method) =>
                        {
                            builder.AppendLine($"public static readonly PyStrObject {method.Name} = PyStrObject.InternPool.FromString(PySpecialNames.{method.Name});");
                        })
                    .ExitBlock()
                    .AppendLine()
                    .AppendLine("internal static partial System.Collections.Generic.IEnumerable<string> EnumerateGeneratedNames()")
                    .EnterBlock()
                        .ForEach(methods, static (builder, method) =>
                        {
                            builder.AppendLine($"yield return {method.Name};");
                        })
                    .ExitBlock()
                .ExitBlock();

            ctx.AddSource("PySpecialNames.g.cs", SourceText.From(builder4.ToString(), Encoding.UTF8));
            
            var builder5 = new IndentedStringBuilder()
                .AppendAutoGeneratedTag()
                .EnableNullable()
                .UsingNamespace("PySharp.Runtime")
                .UsingNamespace("PySharp.Runtime.Calls")
                .UsingNamespace("PySharp.Runtime.PyAttributes")
                .UsingNamespace("System.Collections.Generic")
                .AppendLine()
                .AppendLine("namespace PySharp.Modules.Builtins;")
                .AppendLine()
                .AppendLine("partial class PyTypeObject<TObject>")
                .EnterBlock()
                    .ForEach(methods, static (builder, method) =>
                    {
                        var parameters = string.Join(", ", method.Parameters.Select(p =>
                        {
                            string typeStr = p.Type.Name == "TObject" ? "TObject" : p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            return $"{typeStr} {p.Name}";
                        }));

                        builder
                            .AppendLine("[PySlot]")
                            .AppendLine($"protected virtual partial PyResult {method.Name}({parameters});")
                            .AppendLine();
                    })
                .ExitBlock();

            ctx.AddSource("PyTypeObjectOfT.Partial.g.cs", SourceText.From(builder5.ToString(), Encoding.UTF8));

        });
    }
}
