using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Utility;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration.Internal;

partial class InternalPyTypeObjectGenerator
{
    private static void GenerateSealedFile(SourceProductionContext ctx, List<IMethodSymbol> methods)
    {
        var builder = new IndentedStringBuilder()
            .AppendAutoGeneratedTag()
            .EnableNullable()
            .UsingNamespace("PySharp.Runtime")
            .UsingNamespace("PySharp.Runtime.Calls")
            .UsingNamespace("System.Collections.Generic")
            .AppendLine()
            .AppendLine("namespace PySharp.Modules.Builtins;")
            .AppendLine()
            .AppendLine("partial class PyTypeObject<TObject>")
            .EnterBlock()
                .ForEach(methods, static (builder, method) =>
                {
                    var parametersDef = string.Join(", ", method.Parameters.Select(p =>
                    {
                        string typeStr = p.Type.Name == "TObject" ? "PyObject" : p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        return $"{typeStr} {p.Name}";
                    }));

                    var parametersCall = string.Join(", ", method.Parameters.Select(p =>
                    {
                        return p.Name == "self" ? "selfOfT" : p.Name;
                    }));

                    builder
                        .AppendLine($"private protected sealed override PyResult {method.Name}({parametersDef})")
                        .EnterBlock()
                        .AppendLine($"if (self is not TObject selfOfT)")
                        .Indent()
                        .AppendLine($"return PyResult.TypeError(PySR.Runtime_Type_MethodReceiveSelfWithWrongType, PySpecialNames.{method.Name}, FullName, self.PyType.FullName);")
                        .Dedent()
                        .AppendLine($"return {method.Name}({parametersCall});")
                        .ExitBlock()
                        .AppendLine();
                })
            .ExitBlock();

        ctx.AddSource("PyTypeObjectOfT.Sealed.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
