using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Utility;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration.Internal;

partial class InternalPyTypeObjectGenerator
{
    private static void GenerateSlotsFile(
        SourceProductionContext ctx,
        List<IMethodSymbol> directMethods,
        List<IGrouping<string, IMethodSymbol>> slotsMemberGroups,
        Dictionary<string, (IFieldSymbol field, INamedTypeSymbol type)> slotsMemberFieldTypes)
    {
        var builder = new IndentedStringBuilder()
            .AppendAutoGeneratedTag()
            .EnableNullable()
            .UsingNamespace("PySharp.Runtime.Calls")
            .UsingNamespace("PySharp.Runtime.Calls.Extensions")
            .AppendLine()
            .AppendLine("namespace PySharp.Modules.Builtins;")
            .AppendLine()
            .AppendLine("partial class PyTypeObject")
            .EnterBlock()
                .AppendLine("protected internal sealed partial class PyTypeSlots")
                .EnterBlock();

        // Delegate fields for methods without SlotsMember
        foreach (var method in directMethods)
        {
            var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
            var delegateType = (INamedTypeSymbol)attributeData.ConstructorArguments[1].Value!;
            builder.AppendLine($"internal {delegateType.Name}? {method.Name};");
        }

        // Nested types for each SlotsMember group — generate delegate fields inside the field's type
        foreach (var group in slotsMemberGroups)
        {
            if (!slotsMemberFieldTypes.TryGetValue(group.Key, out var info)) continue;

            var nestedType = info.type;
            builder.AppendLine();
            builder.AppendLine($"internal sealed partial class {nestedType.Name}");
            builder.EnterBlock();

            foreach (var method in group)
            {
                var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                var delegateType = (INamedTypeSymbol)attributeData.ConstructorArguments[1].Value!;
                builder.AppendLine($"internal {delegateType.Name}? {method.Name};");
            }

            builder.ExitBlock();
        }

        // Forwarding accessors for SlotsMember methods — exposes nested type's fields directly on PyTypeSlots
        foreach (var group in slotsMemberGroups)
        {
            if (!slotsMemberFieldTypes.TryGetValue(group.Key, out var info)) continue;
            var fieldName = group.Key;
            foreach (var method in group)
            {
                var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                var delegateType = (INamedTypeSymbol)attributeData.ConstructorArguments[1].Value!;
                builder.AppendLine($"internal {delegateType.Name}? {method.Name} => {fieldName}?.{method.Name};");
            }
        }

        builder
            .AppendLine()
            .AppendLine("internal PyTypeSlots Clone()")
            .EnterBlock()
                .AppendLine("return (PyTypeSlots)MemberwiseClone();")
            .ExitBlock()
            .AppendLine()
            .AppendLine("internal void FillNullWith(PyTypeSlots other)")
            .EnterBlock();

        // FillNullWith: direct fields
        foreach (var method in directMethods)
        {
            builder.AppendLine($"{method.Name} ??= other.{method.Name};");
        }

        // FillNullWith: nested type fields
        foreach (var group in slotsMemberGroups)
        {
            if (!slotsMemberFieldTypes.TryGetValue(group.Key, out var info)) continue;
            var fieldName = group.Key;
            builder.AppendLine($"if (other.{fieldName} != null)");
            builder.EnterBlock();
            builder.AppendLine($"{fieldName} ??= new {info.type.Name}();");
            foreach (var method in group)
            {
                builder.AppendLine($"{fieldName}.{method.Name} ??= other.{fieldName}.{method.Name};");
            }
            builder.ExitBlock();
        }

        builder
            .ExitBlock()
            .AppendLine()
            .AppendLine("internal void TrySetSlot(string name, PyObject value)")
            .EnterBlock()
                .AppendLine("switch (name)")
                .EnterBlock()
                    .AppendLine("case \"__new__\": New = value.ToClsArgsKwargsFunction(); break;");

        // TrySetSlot: direct fields
        foreach (var method in directMethods)
        {
            var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
            var specialName = (string)attributeData.ConstructorArguments[0].Value!;
            var delegateType = (INamedTypeSymbol)attributeData.ConstructorArguments[1].Value!;
            var extMethod = GetExtensionMethodName(delegateType.Name);
            builder.AppendLine($"case \"{specialName}\": {method.Name} = value.{extMethod}(); break;");
        }

        // TrySetSlot: nested type fields
        foreach (var group in slotsMemberGroups)
        {
            if (!slotsMemberFieldTypes.TryGetValue(group.Key, out var info)) continue;
            var fieldName = group.Key;
            foreach (var method in group)
            {
                var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                var specialName = (string)attributeData.ConstructorArguments[0].Value!;
                var delegateType = (INamedTypeSymbol)attributeData.ConstructorArguments[1].Value!;
                var extMethod = GetExtensionMethodName(delegateType.Name);
                builder.AppendLine($"case \"{specialName}\": {fieldName} ??= new(); {fieldName}.{method.Name} = value.{extMethod}(); break;");
            }
        }

        builder
                        .ExitBlock()
                    .ExitBlock()
                .ExitBlock()
            .ExitBlock();

        ctx.AddSource("PyTypeObject.Slots.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
