using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Diagnostics;
using PySharp.SourceGeneration.Utility;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration.Internal;

[Generator]
internal class InternalPyExceptionThrowGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: PySharpTypes.PyExceptionAttribute,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (generatorContext, _) =>
                {
                    var typeSymbol = (INamedTypeSymbol)generatorContext.TargetSymbol;
                    var attribute = typeSymbol.GetAttribute(PySharpTypes.PyExceptionAttribute)!;
                    var filePath = generatorContext.TargetNode.SyntaxTree.FilePath;

                    // Only the PyExceptionObject.Types.cs declarations are processed here; other [PyException] usages are normal skips.
                    if (!filePath.EndsWith("PyExceptionObject.Types.cs"))
                        return null;

                    // An explicitly null qual name is an error carried in the model; an undecodable
                    // constant (e.g. a symbol generated by another generator) is skipped silently.
                    if (!attribute.TryGetRequiredStringArgument(0, "qualName", out var qualName, out var qualNameError))
                    {
                        DebugHelper.AssertNotNull(qualNameError);
                        return DiagnosticOr<string>.From(qualNameError);
                    }

                    if (qualName is "BaseException" or "Exception")
                        return null;

                    return DiagnosticOr<string>.From(qualName);
                })
            .WhereNotNull();

        var collected = provider.Collect();

        context.RegisterSourceOutput(collected, static (context, results) =>
        {
            bool anyDiagnostic = false;
            foreach (var info in results)
            {
                if (!info.HasDiagnostic)
                    continue;

                anyDiagnostic = true;
                context.ReportAll(info.Diagnostics);
            }

            if (anyDiagnostic)
                return;

            var infos = results.Select(static result => result.Value).ToArray();
            GeneratePyResultFile(context, infos);
            GeneratePyCallContextFile(context, infos);
        });
    }

    private static void GeneratePyResultFile(SourceProductionContext context, string[] qualNames)
    {
        var builder = new IndentedStringBuilder();
        builder
            .AppendAutoGeneratedTag()
            .EnableNullable()
            .UsingNamespace("PySharp.Modules.Builtins");

        builder
            .AppendLine("namespace PySharp.Runtime.Calls")
            .EnterBlock()
                .AppendLine("partial struct PyResult")
                .EnterBlock()
                .ForEach(qualNames, static (builder, qualName) =>
                {
                    builder
                         .AppendLine($"public static PyExceptionResult {qualName}(string? format, params ReadOnlySpan<object?> args)")
                        .EnterBlock()
                            .AppendLine($"return RaiseException({GetCSharpTypeName(qualName)}.Shared, format, args);")
                        .ExitBlock();
                })
                .ExitBlock()
            .ExitBlock();

        context.AddSource("PyResult.ExceptionThrows.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static void GeneratePyCallContextFile(SourceProductionContext context, string[] qualNames)
    {
        var builder = new IndentedStringBuilder();
        builder
            .AppendAutoGeneratedTag()
            .EnableNullable()
            .UsingNamespace("PySharp.Modules.Builtins");

        builder
            .AppendLine("namespace PySharp.Runtime.Calls")
            .EnterBlock()
                .AppendLine("partial class PyCallContext")
                .EnterBlock()
                .ForEach(qualNames, static (builder, qualName) =>
                {
                    builder
                        .AppendLine($"internal PyRuntimeException {qualName}(string? format, params ReadOnlySpan<object?> args)")
                        .EnterBlock()
                            .AppendLine($"return ThrowableException({GetCSharpTypeName(qualName)}.Shared, format, args);")
                        .ExitBlock();
                })
                .ExitBlock()
            .ExitBlock();

        context.AddSource("PyCallContext.ExceptionThrows.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static string GetCSharpTypeName(string qualName)
    {
        return $"Py{qualName}ObjectType";
    }
}
