using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Utility;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration.Internal;

[Generator]
internal class InternalPyExceptionThrowGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: PySharpTypes.PyExceptionAttribute,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (generatorContext, _) =>
                {
                    var typeSymbol = (INamedTypeSymbol)generatorContext.TargetSymbol;
                    var attribute = typeSymbol.GetAttribute(PySharpTypes.PyExceptionAttribute)!;
                    var qualName = attribute.GetConstructorArgument<string>(0);
                    var filePath = generatorContext.TargetNode.SyntaxTree.FilePath;

                    if (qualName is null || !filePath.EndsWith("PyExceptionObject.Types.cs") || qualName is "BaseException" or "Exception")
                        return null;

                    var typeName = $"Py{qualName}ObjectType";
                    return new ExceptionThrowInfo(typeName, qualName);
                })
            .Where(static info => info is not null)!;

        var collected = provider.Collect();

        context.RegisterSourceOutput(collected, static (spc, infos) =>
        {
            if (infos.IsEmpty)
                return;

            GeneratePyResultFile(spc, infos);
            GeneratePyCallContextFile(spc, infos);
        });
    }

    private static void GeneratePyResultFile(SourceProductionContext spc, ImmutableArray<ExceptionThrowInfo?> infos)
    {
        var builder = new IndentedStringBuilder();
        builder
            .AppendAutoGeneratedTag()
            .EnableNullable()
            .UsingNamespace("PySharp.Modules.Builtins");

        builder
            .AppendLine("namespace PySharp.Runtime.Calls")
            .EnterBlock()
                .AppendLine("partial struct PyResult")
                .EnterBlock();

        foreach (var info in infos)
        {
            if (info is null)
                continue;
            var methodName = info.QualName;
            builder
                .AppendLine($"public static PyExceptionResult {methodName}(string? format, params ReadOnlySpan<object?> args)")
                .EnterBlock()
                    .AppendLine($"return RaiseException({info.TypeName}.Shared, format, args);")
                .ExitBlock();
        }

        builder
                .ExitBlock()
            .ExitBlock();

        spc.AddSource("PyResult.ExceptionThrows.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static void GeneratePyCallContextFile(SourceProductionContext spc, ImmutableArray<ExceptionThrowInfo?> infos)
    {
        var builder = new IndentedStringBuilder();
        builder
            .AppendAutoGeneratedTag()
            .EnableNullable()
            .UsingNamespace("PySharp.Modules.Builtins");

        builder
            .AppendLine("namespace PySharp.Runtime.Calls")
            .EnterBlock()
                .AppendLine("partial class PyCallContext")
                .EnterBlock();

        foreach (var info in infos)
        {
            if (info is null)
                continue;
            var methodName = info.QualName;
            builder
                .AppendLine($"internal PyRuntimeException {methodName}(string? format, params ReadOnlySpan<object?> args)")
                .EnterBlock()
                    .AppendLine($"return ThrowableException({info.TypeName}.Shared, format, args);")
                .ExitBlock();
        }

        builder
                .ExitBlock()
            .ExitBlock();

        spc.AddSource("PyCallContext.ExceptionThrows.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private sealed class ExceptionThrowInfo
    {
        public ExceptionThrowInfo(string typeName, string qualName)
        {
            TypeName = typeName;
            QualName = qualName;
        }

        public string TypeName { get; }
        public string QualName { get; }
    }
}
