using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Utility;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration.Internal;

partial class InternalPyTypeObjectGenerator
{
    private static void GeneratePartialDeclarationsFile(SourceProductionContext ctx, List<IMethodSymbol> methods)
    {
        var builder = new IndentedStringBuilder()
            .AppendAutoGeneratedTag()
            .EnableNullable()
            .UsingNamespace("PySharp.Runtime")
            .UsingNamespace("PySharp.Runtime.Calls")
            .UsingNamespace("PySharp.Runtime.PyAttributes")
            .UsingNamespace("System.Collections.Generic")
            .AppendLine()
            .AppendLine("namespace PySharp.Modules.Builtins;")
            .AppendLine()
            .AppendLine("partial class PyTypeObject<TObject>")
            .EnterBlock()
                .ForEach(methods, static (builder, method) =>
                {
                    var parameters = string.Join(", ", method.Parameters.Select(p =>
                    {
                        string typeStr = p.Type.Name == "TObject" ? "TObject" : p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        return $"{typeStr} {p.Name}";
                    }));

                    builder
                        .AppendLine($"protected virtual partial PyResult {method.Name}({parameters});")
                        .AppendLine();
                })
            .ExitBlock();

        ctx.AddSource("PyTypeObjectOfT.Partial.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
