using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PySharp.Roslyn.Shared.Utility;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration.Internal;

partial class InternalPyTypeObjectGenerator
{
    // Forward -> reflected virtual pairs. The forward slots of these pairs
    // get SLOT1BINFULL-shaped bridges (typeobject.c slot_nb_add is the
    // reference): the type-safe forward entry for a TObject self, then —
    // once that declines, or when the self position carries a foreign
    // object (the original-order call of a right-side type, CPython
    // binary_op1's third step) — the reflected entry with the pair flipped
    // back, so a hand-written R* override stays reachable without a
    // dedicated reflected slot. Every other bridge keeps the strict
    // wrong-receiver TypeError guard.
    private static readonly Dictionary<string, string> ReflectedSlotPairs = new()
    {
        ["Add"] = "RAdd",
        ["Sub"] = "RSub",
        ["Mul"] = "RMul",
        ["MatMul"] = "RMatMul",
        ["TrueDiv"] = "RTrueDiv",
        ["FloorDiv"] = "RFloorDiv",
        ["Mod"] = "RMod",
        ["DivMod"] = "RDivMod",
        ["Pow"] = "RPow",
        ["LShift"] = "RLShift",
        ["RShift"] = "RRShift",
        ["And"] = "RAnd",
        ["Xor"] = "RXor",
        ["Or"] = "ROr",
    };

    private static void GenerateSealedFile(SourceProductionContext ctx, List<IMethodSymbol> methods)
    {
        var builder = new IndentedStringBuilder()
            .AppendAutoGeneratedTag()
            .EnableNullable()
            .UsingNamespace("PySharp.Runtime")
            .UsingNamespace("PySharp.Runtime.Calls")
            .UsingNamespace("System.Collections.Generic")
            .AppendLine()
            .AppendLine("namespace PySharp.Modules.Builtins;")
            .AppendLine()
            .AppendLine("partial class PyTypeObject<TObject>")
            .EnterBlock()
                .ForEach(methods, (builder, method) =>
                {
                    var parametersDef = string.Join(", ", method.Parameters.Select(p =>
                    {
                        string typeStr = p.Type.Name is "TObject" ? "PyObject" : p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        return $"{typeStr} {p.Name}";
                    }));

                    var parametersCall = string.Join(", ", method.Parameters.Select(p =>
                    {
                        return p.Name is "self" ? "selfOfT" : p.Name;
                    }));

                    builder
                        .AppendLine($"protected internal sealed override PyResult {method.Name}{BridgeSuffix}({parametersDef})")
                        .EnterBlock();

                    if (ReflectedSlotPairs.TryGetValue(method.Name, out var reflected))
                    {
                        // the forward pass keeps the argument order; the
                        // reflected fallback swaps self and other and keeps
                        // any third argument (pow's modulo) in place
                        var reflectedCall = string.Join(", ", method.Parameters.Select(p =>
                        {
                            return p.Name switch
                            {
                                "self" => "otherOfT",
                                "other" => "self",
                                _ => p.Name,
                            };
                        }));

                        builder
                            .AppendLine("if (self is TObject selfOfT)")
                            .EnterBlock()
                            .AppendLine($"var result = {method.Name}({parametersCall});")
                            .AppendLine("if (!result.IsNotImplemented)")
                            .Indent()
                            .AppendLine("return result;")
                            .Dedent()
                            .AppendLine("// binary_op1: identical operand layouts resolve to a single")
                            .AppendLine("// shared slot — the reflected method never runs")
                            .AppendLine("if (other is TObject)")
                            .Indent()
                            .AppendLine("return PyNotImplementedObject.NotImplemented;")
                            .Dedent()
                            .ExitBlock()
                            .AppendLine("if (other is TObject otherOfT)")
                            .EnterBlock()
                            .AppendLine($"var result = {reflected}({reflectedCall});")
                            .AppendLine("if (!result.IsNotImplemented)")
                            .Indent()
                            .AppendLine("return result;")
                            .Dedent()
                            .ExitBlock()
                            .AppendLine("return PyNotImplementedObject.NotImplemented;");
                    }
                    else
                    {
                        builder
                            .AppendLine($"if (self is not TObject selfOfT)")
                            .Indent()
                            .AppendLine($"return PyResult.TypeError(PySR.Runtime_Type_MethodReceiveSelfWithWrongType, PySpecialNames.{method.Name}, QualName, self.PyType.QualName);")
                            .Dedent()
                            .AppendLine($"return {method.Name}({parametersCall});");
                    }

                    builder
                        .ExitBlock()
                        .AppendLine();
                })
            .ExitBlock();

        ctx.AddSource("PyTypeObjectOfT.Sealed.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
