using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration.Internal;

[Generator]
public class InternalPyTypeObjectGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var declarationsProvider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax { Identifier.ValueText: "Declarations" },
            transform: static (ctx, _) =>
            {
                var classDeclaration = (ClassDeclarationSyntax)ctx.Node;
                var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDeclaration);

                if (symbol is { Name: "Declarations" } &&
                    symbol.ContainingType is { Name: "PyTypeObject" } &&
                    symbol.ContainingNamespace.ToDisplayString() == "PySharp.Modules.Builtins")
                {
                    return symbol;
                }

                return null;
            }
        ).Where(static x => x is not null);

        context.RegisterSourceOutput(declarationsProvider, static (ctx, symbol) =>
        {
            var methods = ((INamedTypeSymbol)symbol!).GetMembers().OfType<IMethodSymbol>().Where(m => m.IsPartialDefinition);

            var builder = new IndentedStringBuilder()
                .AppendLine("// <auto-generated/>")
                .AppendLine("using PySharp.Runtime.Calls;")
                .AppendLine("using System.Collections.Generic;")
                .AppendLine("using System.Diagnostics;")
                .AppendLine()
                .AppendLine("namespace PySharp.Modules.Builtins;")
                .AppendLine()
                .AppendLine("partial class PyTypeObject")
                .EnterBlock()
                    .ForEach(methods, static (builder, method) =>
                    {
                        var parameters = string.Join(", ", method.Parameters.Select(p => 
                        {
                            string typeStr = p.Type.Name == "TObject" ? "PyObject" : p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            return $"{typeStr} {p.Name}";
                        }));
                    
                        builder
                            .AppendLine($"private protected virtual PyResult {method.Name}({parameters})")
                            .EnterBlock()
                            .AppendLine("throw new UnreachableException(\"Implemented by PyTypeObject<TObject>\");")
                            .ExitBlock()
                            .AppendLine();
                    })
                .ExitBlock();

            ctx.AddSource("PyTypeObject.Virtual.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));

            var builder2 = new IndentedStringBuilder()
                .AppendLine("// <auto-generated/>")
                .AppendLine("using PySharp.Runtime;")
                .AppendLine("using PySharp.Runtime.Calls;")
                .AppendLine("using System.Collections.Generic;")
                .AppendLine()
                .AppendLine("namespace PySharp.Modules.Builtins;")
                .AppendLine()
                .AppendLine("partial class PyTypeObject<TObject>")
                .EnterBlock()
                .ForEach(methods, static (b, method) =>
                {
                    var parametersDef = string.Join(", ", method.Parameters.Select(p => 
                    {
                        string typeStr = p.Type.Name == "TObject" ? "PyObject" : p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        return $"{typeStr} {p.Name}";
                    }));

                    var parametersCall = string.Join(", ", method.Parameters.Select(p => 
                    {
                        return p.Name == "self" ? "selfOfT" : p.Name;
                    }));

                    b.AppendLine($"private protected sealed override PyResult {method.Name}({parametersDef})")
                     .EnterBlock()
                     .AppendLine($"if (self is not TObject selfOfT)")
                     .Indent()
                     .AppendLine($"return PyResult.TypeError(PySR.Runtime_Type_MethodReceiveSelfWithWrongType, PySpecialNames.{method.Name}, FullName, self.PyType.FullName);")
                     .Dedent()
                     .AppendLine($"return {method.Name}({parametersCall});")
                     .ExitBlock()
                     .AppendLine();
                })
                .ExitBlock();

            ctx.AddSource("PyTypeObjectOfT.Sealed.g.cs", SourceText.From(builder2.ToString(), Encoding.UTF8));

            var builder3 = new IndentedStringBuilder()
                .AppendLine("// <auto-generated/>")
                .AppendLine("using PySharp.Runtime.Calls;")
                .AppendLine("using PySharp.Runtime.Calls.Extensions;")
                .AppendLine()
                .AppendLine("namespace PySharp.Modules.Builtins;")
                .AppendLine()
                .AppendLine("partial class PyTypeObject")
                .EnterBlock()
                .AppendLine("protected internal sealed partial class PyTypeSlots")
                .EnterBlock()
                .ForEach(methods, static (b, method) =>
                {
                    var attributeData = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                    if (attributeData != null)
                    {
                        var delegateType = attributeData.ConstructorArguments[1].Value as INamedTypeSymbol;
                        if (delegateType != null)
                        {
                            b.AppendLine($"internal {delegateType.Name}? {method.Name};");
                        }
                    }
                })
                .AppendLine()
                .AppendLine("internal PyTypeSlots Clone()")
                .EnterBlock()
                .AppendLine("return (PyTypeSlots)MemberwiseClone();")
                .ExitBlock()
                .AppendLine()
                .AppendLine("internal void FillNullWith(PyTypeSlots other)")
                .EnterBlock()
                .ForEach(methods, static (b, method) =>
                {
                    var attributeData = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                    if (attributeData != null)
                    {
                        b.AppendLine($"{method.Name} ??= other.{method.Name};");
                    }
                })
                .ExitBlock()
                .AppendLine()
                .AppendLine("internal void TrySetSlot(string name, PyObject value)")
                .EnterBlock()
                .AppendLine("switch (name)")
                .EnterBlock()
                .AppendLine("case \"__new__\": New = value.ToClsArgsKwargsFunction(); break;")
                .ForEach(methods, static (b, method) =>
                {
                    var attributeData = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                    if (attributeData != null)
                    {
                        var specialName = attributeData.ConstructorArguments[0].Value as string;
                        var delegateType = attributeData.ConstructorArguments[1].Value as INamedTypeSymbol;
                        if (specialName != null && delegateType != null)
                        {
                            string delegateName = delegateType.Name;
                            string extMethod = delegateName.StartsWith("Py") ? "To" + delegateName.Substring(2) : "To" + delegateName;
                            b.AppendLine($"case \"{specialName}\": {method.Name} = value.{extMethod}(); break;");
                        }
                    }
                })
                .ExitBlock()
                .ExitBlock()
                .ExitBlock()
                .ExitBlock();

            ctx.AddSource("PyTypeObject.Slots.g.cs", SourceText.From(builder3.ToString(), Encoding.UTF8));

            var builder4 = new IndentedStringBuilder()
                .AppendLine("// <auto-generated/>")
                .AppendLine("namespace PySharp.Runtime;")
                .AppendLine()
                .AppendLine("public static partial class PySpecialNames")
                .EnterBlock()
                .ForEach(methods, static (b, method) =>
                {
                    var attributeData = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                    if (attributeData != null)
                    {
                        var specialName = attributeData.ConstructorArguments[0].Value as string;
                        if (specialName != null)
                        {
                            b.AppendLine($"public const string {method.Name} = \"{specialName}\";");
                        }
                    }
                })
                .ExitBlock();

            ctx.AddSource("PySpecialNames.g.cs", SourceText.From(builder4.ToString(), Encoding.UTF8));
        });
    }
}
