using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Utility;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration.Internal;

partial class InternalPyTypeObjectGenerator
{
    private static void GenerateSpecialNamesFile(SourceProductionContext ctx, List<IMethodSymbol> methods)
    {
        var builder = new IndentedStringBuilder()
            .AppendAutoGeneratedTag()
            .EnableNullable()
            .UsingNamespace("PySharp.Modules.Builtins")
            .AppendLine("namespace PySharp.Runtime;")
            .AppendLine()
            .AppendLine("partial class PySpecialNames")
            .EnterBlock()
                .ForEach(methods, static (builder, method) =>
                {
                    var attributeData = method.GetAttributes().First(a => a.AttributeClass?.Name == "PySpecialMethodAttribute");
                    var specialName = attributeData.GetConstructorArgument<string>(0);
                    if (specialName is null) return;
                    builder.AppendLine($"public const string {method.Name} = \"{specialName}\";");
                })
                .AppendLine()
                .AppendLine("partial class Interned")
                .EnterBlock()
                    .ForEach(methods, static (builder, method) =>
                    {
                        builder.AppendLine($"public static readonly PyStrObject {method.Name} = PyStrObject.InternPool.FromString(PySpecialNames.{method.Name});");
                    })
                .ExitBlock()
                .AppendLine()
                .AppendLine("internal static partial System.Collections.Generic.IEnumerable<string> EnumerateGeneratedNames()")
                .EnterBlock()
                    .ForEach(methods, static (builder, method) =>
                    {
                        builder.AppendLine($"yield return {method.Name};");
                    })
                .ExitBlock()
            .ExitBlock();

        ctx.AddSource("PySpecialNames.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
