global using PySharp.Resources;
global using PySharp.Runtime.Calls.Extensions;

/// <summary>
/// Attribute to mark code that is generated by AI and has not been reviewed by a human.
/// This attribute indicates that the annotated code may not have undergone manual verification,
/// and is intended to distinguish AI-generated content from human-written code for later review,
/// maintenance, or special handling.
/// </summary>
[AttributeUsage(AttributeTargets.All)]
internal sealed class AIGeneratedAttribute : Attribute;