<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Silencersn</Authors>
    <Version>0.37</Version>
    <Copyright>Copyright © 2025-2026 Silencersn. All rights reserved.</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PySharp.SourceGeneration\PySharp.SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <None Include="..\PySharp.SourceGeneration\bin\$(Configuration)\netstandard2.0\PySharp.SourceGeneration.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PySharp.SourceGeneration.Internal\PySharp.SourceGeneration.Internal.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PySharp.Analyzer.Internal\PySharp.Analyzer.Internal.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PySharp.Analyzer\PySharp.Analyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <None Include="..\PySharp.Analyzer\bin\$(Configuration)\netstandard2.0\PySharp.Analyzer.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Lib\**\*.py" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\Warnings\" />
  </ItemGroup>

</Project>
