using PySharp.Runtime.PyAttributes;

namespace PySharp.Modules.Builtins;

[PyModuleInclude(PyModuleIncludeScheme.StaticMembers, typeof(PyBuiltinFunctions))]

// Built-in types
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyStrObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyIntObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyFloatObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyTupleObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyDictObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyBoolObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyListObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyTypeObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyRangeObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyZipObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyPropertyObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PySuperObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PySliceObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyMapObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PySetObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyFrozenSetObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyComplexObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyStaticMethodObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyClassMethodObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyEnumerateObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyReversedObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyFilterObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyBytesObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyByteArrayObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyMemoryViewObjectType))]

// Special singletons
[PyModuleInclude(PyModuleIncludeScheme.ExplicitMember, "Ellipsis", typeof(PyEllipsisObject), nameof(PyEllipsisObject.Ellipsis))]
[PyModuleInclude(PyModuleIncludeScheme.ExplicitMember, "NotImplemented", typeof(PyNotImplementedObject), nameof(PyNotImplementedObject.NotImplemented))]

// Base exception hierarchy
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyBaseExceptionObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PySystemExitObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyExceptionObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyTypeErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyStopIterationObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyAttributeErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyLookupErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyKeyErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyIndexErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyValueErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyNameErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyImportErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyModuleNotFoundErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PySyntaxErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyIndentationErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyArithmeticErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyZeroDivisionErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyAssertionErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyUnboundLocalErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyRuntimeErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyGeneratorExitObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyBaseExceptionGroupObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyExceptionGroupObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyKeyboardInterruptObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyFloatingPointErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyOverflowErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyBufferErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyEOFErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyMemoryErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyOSErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyBlockingIOErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyChildProcessErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyConnectionErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyBrokenPipeErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyConnectionAbortedErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyConnectionRefusedErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyConnectionResetErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyFileExistsErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyFileNotFoundErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyInterruptedErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyIsADirectoryErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyNotADirectoryErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyPermissionErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyProcessLookupErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyTimeoutErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyReferenceErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyNotImplementedErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyPythonFinalizationErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyRecursionErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyStopAsyncIterationObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyTabErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PySystemErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyUnicodeErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyUnicodeEncodeErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyUnicodeDecodeErrorObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyUnicodeTranslateErrorObjectType))]

// Warning hierarchy
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyWarningObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyUserWarningObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PySyntaxWarningObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyDeprecationWarningObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyBytesWarningObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyEncodingWarningObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyFutureWarningObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyImportWarningObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyPendingDeprecationWarningObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyResourceWarningObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyRuntimeWarningObjectType))]
[PyModuleInclude(PyModuleIncludeScheme.TypeSingleton, typeof(PyUnicodeWarningObjectType))]
public partial class PyBuiltinsModuleObject : PyModuleObject
{
    public override string? Origin => "built-in";

    public PyBuiltinsModuleObject() : base("builtins")
    {
    }
}
