using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace PySharp.Tests;

/// <summary>
/// Shared driver for the CPython output-comparison tests generated by
/// <c>PySharp.Tests.SourceGeneration.PyFixtureTestsGenerator</c> (the
/// <c>PyFileCpythonTests</c> class). Each fixture runs as a script under both
/// PySharp.Console and a local CPython 3.14, and the two runs must agree.
///
/// "Agree" means: equal exit codes, and for two successful runs equal stdout
/// after normalization (CRLF/LF and line-trailing whitespace, 0x addresses,
/// absolute paths), or for two failing runs the same final exception type.
/// stderr content is deliberately not compared: warning and unraisable
/// formatting still differs (tracked as known gaps), and a fixture's stderr is
/// diagnostic output, not part of its behavior contract.
///
/// Both sides run as subprocesses so behaviors like exit codes, argv
/// injection and the script directory on sys.path are observed exactly as a
/// user would; each run gets a fresh temporary working directory so fixtures
/// using relative file I/O cannot leak into the corpus or the repository.
///
/// When no CPython 3.14 can be located the comparison tests are inconclusive,
/// never failures: the layer is an opt-in-by-environment check, not a hard
/// dependency (docs/reference/contributing/test-corpus.md).
/// </summary>
internal static class PyCpythonDiffRunner
{
    private const int TimeoutMs = 60_000;

    /// <summary>
    /// Caps concurrent interpreter subprocesses: the fixture tests run with
    /// method-level parallelism and would otherwise start hundreds of
    /// processes at once.
    /// </summary>
    private static readonly SemaphoreSlim Gate = new(initialCount: 8);

    private static readonly Lazy<string?> ConsoleExeCache = new(FindPySharpConsole);

    private static readonly Lazy<(Cpython? Interpreter, string ProbeLog)> CpythonCache =
        new(FindCpythonCore);

    private static readonly Regex AddressRegex = new("0x[0-9a-fA-F]+", RegexOptions.Compiled);

    private static readonly Regex WindowsPathRegex = new(@"[A-Za-z]:[/\\][^\s'""<>]*", RegexOptions.Compiled);

    /// <summary>
    /// Final exception type in a traceback ("ValueError", "collections.Error",
    /// "SystemExit"), taken from the last type-shaped line of stderr.
    /// </summary>
    private static readonly Regex ExceptionTypeRegex = new(
        @"^([A-Za-z_][\w.]*(?:Error|Exception|Warning|Exit|Interrupt|StopIteration|BaseException))(?::|$)",
        RegexOptions.Multiline | RegexOptions.Compiled);

    private sealed record RunResult(int ExitCode, string StdOut, string StdErr, bool TimedOut);

    private sealed record Cpython(string ExePath, string Version);

    /// <summary>
    /// Locates the PySharp.Console build output by walking up from the test
    /// output to the repository root. Cached for the diff tests; also used by
    /// the hand-written crash tests, which spawn child processes for the same
    /// reason (a crash must not kill the test host).
    /// </summary>
    internal static string? FindPySharpConsole()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "PySharp.slnx")))
            dir = dir.Parent;
        if (dir is null)
            return null;
        foreach (var cfg in new[] { "Debug", "Release" })
        {
            var candidate = Path.Combine(dir.FullName, "PySharp.Console", "bin", cfg, "net10.0", "PySharp.Console.exe");
            if (File.Exists(candidate))
                return candidate;
        }
        return null;
    }

    internal static void Run(string fileName)
    {
        var consoleExe = ConsoleExeCache.Value;
        if (consoleExe is null)
            Assert.Inconclusive("PySharp.Console build output not found; build PySharp.Console first");

        var (cpython, probeLog) = CpythonCache.Value;
        if (cpython is null)
        {
            Assert.Inconclusive(
                "CPython 3.14 not found, fixture output comparison skipped " +
                $"(probed: {probeLog}). Set PYSHARP_CPYTHON to a Python 3.14 " +
                "executable to enable it.");
        }

        var fixturePath = Path.Combine(AppContext.BaseDirectory, "test_pyfiles", fileName);
        Assert.IsTrue(File.Exists(fixturePath), $"fixture not found: {fixturePath}");

        Gate.Wait();
        try
        {
            var workDir = Path.Combine(Path.GetTempPath(), $"pydiff_{Path.GetFileNameWithoutExtension(fileName)}_{Guid.NewGuid():N}");
            Directory.CreateDirectory(workDir);
            try
            {
                // Reference side first: the comparison asserts that PySharp
                // matches CPython, so CPython's result is the baseline.
                var cpyResult = RunProcess(cpython.ExePath, new[] { "-B", fixturePath }, workDir);
                var psResult = RunProcess(consoleExe, new[] { fixturePath }, workDir);
                CompareAndAssert(fileName, cpyResult, psResult);
            }
            finally
            {
                try { Directory.Delete(workDir, recursive: true); } catch (IOException) { }
            }
        }
        finally
        {
            Gate.Release();
        }
    }

    private static void CompareAndAssert(string fileName, RunResult cpy, RunResult ps)
    {
        var context = $"{fileName}: CPython exit {FormatExit(cpy)}, PySharp exit {FormatExit(ps)}";
        if (cpy.TimedOut || ps.TimedOut)
            Assert.Fail($"{context} — timed out ({(cpy.TimedOut ? "CPython" : "PySharp")} side)");

        if (cpy.ExitCode == 0 && ps.ExitCode == 0)
        {
            var cpyOut = Normalize(cpy.StdOut);
            var psOut = Normalize(ps.StdOut);
            if (cpyOut != psOut)
                Assert.AreEqual(cpyOut, psOut, $"{context} — stdout differs\n{StdoutDiff(cpyOut, psOut)}\n{StderrTails(cpy, ps)}");
            return;
        }

        if (cpy.ExitCode != 0 && ps.ExitCode != 0)
        {
            var cpyType = ExceptionType(cpy.StdErr);
            var psType = ExceptionType(ps.StdErr);
            if (cpyType != psType)
                Assert.AreEqual(
                    cpyType, psType,
                    $"{context} — both sides failed but with different exceptions\n{StderrTails(cpy, ps)}");
            return;
        }

        Assert.Fail($"{context} — exit-code parity: only one side failed\n{StderrTails(cpy, ps)}");
    }

    private static string FormatExit(RunResult result) =>
        result.TimedOut ? "timeout" : result.ExitCode.ToString(System.Globalization.CultureInfo.InvariantCulture);

    private static string ExceptionType(string stderr)
    {
        var matches = ExceptionTypeRegex.Matches(stderr);
        return matches.Count > 0 ? matches[^1].Groups[1].Value : "?";
    }

    private static string StdoutDiff(string cpyOut, string psOut)
    {
        var cpyLines = cpyOut.Split('\n');
        var psLines = psOut.Split('\n');
        var shared = Math.Min(cpyLines.Length, psLines.Length);
        var first = 0;
        while (first < shared && cpyLines[first] == psLines[first])
            first++;
        var from = Math.Max(0, first - 2);
        var cpyContext = string.Join('\n', cpyLines[from..Math.Min(cpyLines.Length, first + 3)]);
        var psContext = string.Join('\n', psLines[from..Math.Min(psLines.Length, first + 3)]);
        return $"first diff at line {first + 1}:\nCPython: {cpyContext}\nPySharp: {psContext}";
    }

    private static string StderrTails(RunResult cpy, RunResult ps) =>
        $"CPython stderr tail: {Tail(cpy.StdErr)}\nPySharp stderr tail: {Tail(ps.StdErr)}";

    private static string Tail(string text)
    {
        text = text.Replace("\r\n", "\n").Trim();
        return text.Length <= 1200 ? text : "…" + text[^1200..];
    }

    /// <summary>
    /// Normalizes captured stdout for comparison: line endings and
    /// line-trailing whitespace (PySharp writes raw LF where a Windows
    /// CPython pipe delivers CRLF), object addresses in default reprs, and
    /// absolute paths. Content that survives this is the behavior contract.
    /// </summary>
    internal static string Normalize(string text)
    {
        var lines = text.Replace("\r\n", "\n").Split('\n');
        for (var i = 0; i < lines.Length; i++)
            lines[i] = lines[i].TrimEnd();
        var start = 0;
        var end = lines.Length;
        while (start < end && lines[start].Length == 0)
            start++;
        while (end > start && lines[end - 1].Length == 0)
            end--;
        var normalized = string.Join('\n', lines[start..end]);
        normalized = AddressRegex.Replace(normalized, "0xADDR");
        return WindowsPathRegex.Replace(normalized, "PATH");
    }

    private static RunResult RunProcess(string exe, string[] args, string workDir)
    {
        var psi = new ProcessStartInfo(exe)
        {
            UseShellExecute = false,
            WorkingDirectory = workDir,
            RedirectStandardInput = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            StandardOutputEncoding = Encoding.UTF8,
            StandardErrorEncoding = Encoding.UTF8,
        };
        foreach (var arg in args)
            psi.ArgumentList.Add(arg);

        using var process = Process.Start(psi)!;
        // Closing stdin gives fixtures that call input() a symmetric EOFError
        // on both sides instead of hanging.
        process.StandardInput.Close();
        var outTask = process.StandardOutput.ReadToEndAsync();
        var errTask = process.StandardError.ReadToEndAsync();
        // Async reads: a crashed child may linger in Windows Error Reporting
        // with its pipes open, so the bounded exit wait must come before the
        // results are collected.
        var timedOut = !process.WaitForExit(TimeoutMs);
        if (timedOut)
            process.Kill();
        return new RunResult(
            process.HasExited ? process.ExitCode : -1,
            outTask.Result,
            errTask.Result,
            timedOut);
    }

    private static (Cpython?, string) FindCpythonCore()
    {
        var probes = new List<(string Description, string? ExePath, string[] Args)>
        {
            ("PYSHARP_CPYTHON", Environment.GetEnvironmentVariable("PYSHARP_CPYTHON"), Array.Empty<string>()),
            ("py -3.14", "py", new[] { "-3.14", "--version" }),
            ("python", "python", new[] { "--version" }),
            ("python3", "python3", new[] { "--version" }),
        };

        var log = new StringBuilder();
        foreach (var (description, exePath, args) in probes)
        {
            if (string.IsNullOrEmpty(exePath))
            {
                log.Append(description).Append(": not set/not found; ");
                continue;
            }

            try
            {
                var psi = new ProcessStartInfo(exePath)
                {
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                };
                foreach (var arg in args)
                    psi.ArgumentList.Add(arg);
                using var process = Process.Start(psi)!;
                var version = process.StandardOutput.ReadToEnd() + process.StandardError.ReadToEnd();
                if (!process.WaitForExit(10_000))
                {
                    process.Kill();
                    log.Append(description).Append(": did not answer --version in time; ");
                    continue;
                }

                version = version.Trim();
                if (process.ExitCode == 0 && version.StartsWith("Python 3.14", StringComparison.Ordinal))
                    return (new Cpython(exePath, version), log.ToString());
                log.Append(description).Append(": ").Append(version).Append("; ");
            }
            catch (Exception ex) when (ex is System.ComponentModel.Win32Exception or IOException)
            {
                log.Append(description).Append(": failed to launch (").Append(ex.Message).Append("); ");
            }
        }

        return (null, log.ToString().TrimEnd(';', ' '));
    }
}
