using Microsoft.VisualStudio.TestTools.UnitTesting;
using PySharp.Runtime;

namespace PySharp.Tests;

/// <summary>
/// Shared driver for the fixture tests generated by
/// <c>PySharp.Tests.SourceGeneration.PyFixtureTestsGenerator</c>.
///
/// Fixture stdout/stderr (including the trailing "... passed" markers) is for
/// local debugging only and is never asserted on: a fixture passes when it
/// runs to completion and fails when an exception escapes. Comparing fixture
/// output against a local CPython 3.14 is the job of the generated
/// PyFileCpythonTests class, driven by <see cref="PyCpythonDiffRunner"/>.
/// </summary>
internal static class PyFixtureRunner
{
    internal static void Run(string fileName)
    {
        var module = PyInterpreter.RunFile(Path.Combine("test_pyfiles", fileName));
        Assert.IsNotNull(module);
    }
}
