namespace PySharp.Runtime.PyAttributes;

/// <summary>
/// Declares a partial property whose implementation is generated by the PyExport source generator.
/// The generator reads the <see cref="PyFunctionParametersAttribute"/> from each referenced method
/// at compile time, so constructing the exported member requires no runtime reflection.
/// </summary>
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
public sealed class PyExportAttribute : PyAttribute
{
    public PyExportAttribute(string name, params string[] methods)
    {
        ArgumentNullException.ThrowIfNull(name);
        ArgumentNullException.ThrowIfNull(methods);

        Name = name;
        Methods = methods;
    }

    /// <summary>The Python-facing name of the exported member (e.g. "getattr").</summary>
    public string Name { get; set; }

    /// <summary>The implementation method names, referenced via nameof(...).</summary>
    public string[] Methods { get; set; }
}
