using PySharp.SourceGeneration.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace PySharp.SourceGeneration.Utility;

/// <summary>
/// Strict attribute-argument reading extensions: on failure they produce an
/// <see cref="DiagnosticInfo"/> instead of silently returning a default value.
/// Call these only during the transform stage (they only produce errors, they do not report them);
/// the generator carries the errors along with its model (via <see cref="DiagnosticOr{T}"/>) and
/// reports them in the RegisterSourceOutput stage.
/// Convention: returning true means the value is valid and error is null; returning false with a
/// non-null error means an argument error; returning false with a null error means the argument was
/// not provided (optional) or its constant could not be decoded (e.g. a symbol generated by another
/// generator in a later pass), so the caller should fall back silently.
/// </summary>
internal static class AttributeDataStrictExtensions
{
    public static bool TryGetNamedArgument(this AttributeData attributeData, string key, out TypedConstant value)
    {
        foreach (var pair in attributeData.NamedArguments)
        {
            if (pair.Key != key)
                continue;

            value = pair.Value;
            return true;
        }

        value = default;
        return false;
    }

    /// <summary>
    /// Tries to read a required constructor string argument.
    /// Returns true with a valid value; returns false with a non-null error when the argument was
    /// explicitly null (PYARG002); returns false with a null error when the constant is missing or
    /// undecodable (e.g. a symbol generated by another generator) — fall back silently.
    /// </summary>
    public static bool TryGetRequiredStringArgument(
        this AttributeData attributeData,
        int index,
        string argumentName,
        [NotNullWhen(true)] out string? value,
        out DiagnosticInfo? error)
    {
        var args = attributeData.ConstructorArguments;
        if ((uint)index >= (uint)args.Length)
        {
            // Out-of-range index usually means the attribute constant could not be decoded yet
            // (e.g. it references a name generated by another generator in a later pass).
            // Fall back silently instead of reporting, to avoid false positives on valid code.
            value = null;
            error = null;
            return false;
        }

        var constant = args[index];
        if (constant.Value is string s)
        {
            value = s;
            error = null;
            return true;
        }

        if (constant.Kind == TypedConstantKind.Error || constant.Value is not null)
        {
            // Error constants cannot be decoded reliably; fall back silently (the compiler already reports type errors).
            value = null;
            error = null;
            return false;
        }

        // Value is null (explicitly passed null by the user)
        value = null;
        error = DiagnosticInfo.RequiredArgumentNull(attributeData, argumentName);
        return false;
    }

    /// <summary>
    /// Tries to read a Type argument from the constructor.
    /// Returns true with a valid type; returns false with a null error when the constant is missing or
    /// undecodable (e.g. a generated symbol not yet available) — fall back silently.
    /// </summary>
    public static bool TryGetTypeArgument(
        this AttributeData attributeData,
        int index,
        string argumentName,
        [NotNullWhen(true)] out ITypeSymbol? value,
        out DiagnosticInfo? error)
    {
        var args = attributeData.ConstructorArguments;
        if ((uint)index >= (uint)args.Length)
        {
            // Undecodable constant (e.g. generated symbol not yet available): fall back silently.
            value = null;
            error = null;
            return false;
        }

        var constant = args[index];
        if (constant.Kind != TypedConstantKind.Type || constant.Value is not ITypeSymbol typeSymbol)
        {
            // Error constants cannot be decoded reliably; fall back silently (the compiler already reports type errors).
            value = null;
            error = null;
            return false;
        }

        value = typeSymbol;
        error = null;
        return true;
    }
}
