using System;
using System.Collections.Generic;

namespace PySharp.SourceGeneration.Utility;

internal static class IndentedStringBuilderExtensions
{
    public static IndentedStringBuilder ForEach<T>(this IndentedStringBuilder builder, IEnumerable<T> values, Action<IndentedStringBuilder, T> action)
    {
        foreach (var value in values)
            action(builder, value);
        return builder;
    }

    public static IndentedStringBuilder If(this IndentedStringBuilder builder, bool condition, Action<IndentedStringBuilder> action)
    {
        if (condition)
            action(builder);
        return builder;
    }



    public static IndentedStringBuilder EnterBlock(this IndentedStringBuilder builder)
    {
        return builder.AppendLine('{').Indent();
    }
    public static IndentedStringBuilder ExitBlock(this IndentedStringBuilder builder)
    {
        return builder.Dedent().AppendLine('}');
    }

    public static IndentedStringBuilder UsingNamespace(this IndentedStringBuilder builder, string namespaceName)
    {
        return builder.AppendLine($"using {namespaceName};");
    }


    public static IndentedStringBuilder AppendLineComment(this IndentedStringBuilder builder, string comment)
    {
        return builder.AppendLine($"// {comment}");
    }
    public static IndentedStringBuilder AppendAutoGeneratedTag(this IndentedStringBuilder builder)
    {
        return builder.AppendLineComment("<auto-generated/>");
    }

    public static IndentedStringBuilder EnableNullable(this IndentedStringBuilder builder)
    {
        return builder.AppendLine($"#nullable enable");
    }
}
