using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration;

[Generator]
public class PyExceptionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: PySharpTypes.PyExceptionAttribute,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (generatorContext, _) =>
                {
                    var typeSymbol = (INamedTypeSymbol)generatorContext.TargetSymbol;
                    var attribute = typeSymbol.GetAttribute(PySharpTypes.PyExceptionAttribute)!;

                    var @namespace = typeSymbol.ContainingNamespace.IsGlobalNamespace
                        ? string.Empty
                        : typeSymbol.ContainingNamespace.ToDisplayString();

                    // Extract Bases array from the attribute
                    var baseTypes = new List<ITypeSymbol>();
                    bool foundBases = false;

                    foreach (var pair in attribute.NamedArguments)
                    {
                        if (pair.Key != "Bases")
                            continue;

                        foundBases = true;

                        if (pair.Value.Kind != TypedConstantKind.Array)
                            continue;

                        foreach (var element in pair.Value.Values)
                        {
                            if (element.Kind == TypedConstantKind.Type && element.Value is ITypeSymbol baseType)
                                baseTypes.Add(baseType);
                        }
                    }

                    // Default to PyExceptionObjectType if not specified or empty
                    if (!foundBases || baseTypes.Count is 0)
                    {
                        var compilation = generatorContext.SemanticModel.Compilation;
                        var defaultBase = compilation.GetTypeByMetadataName("PySharp.Modules.Builtins.PyExceptionObjectType");
                        if (defaultBase is not null)
                            baseTypes.Add(defaultBase);
                    }

                    return new PyExceptionInfo(@namespace, typeSymbol.Name, baseTypes);
                });

        context.RegisterSourceOutput(provider, (spc, info) =>
        {
            if (info.BaseTypes.Count is 0)
                return;

            var builder = new IndentedStringBuilder();
            builder
                .AppendAutoGeneratedTag()
                .UsingNamespace("System")
                .UsingNamespace("PySharp.Runtime")
                .UsingNamespace("PySharp.Modules.Builtins");

            var basesExpr = string.Join(", ", info.BaseTypes.Select(static t => $"{t.Name}.Shared"));

            builder
                .AppendLine($"namespace {info.Namespace}")
                .EnterBlock()
                    .AppendLine($"partial class {info.TypeName} : IPyException<{info.TypeName}>")
                    .EnterBlock()
                        .AppendLine($"public sealed override IReadOnlyList<PyTypeObject> Bases => [{basesExpr}];")
                    .ExitBlock()
                .ExitBlock();

            spc.AddSource($"{info.TypeName}.Exception.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        });
    }

    public class PyExceptionInfo
    {
        public PyExceptionInfo(string @namespace, string typeName, List<ITypeSymbol> baseTypes)
        {
            Namespace = @namespace;
            TypeName = typeName;
            BaseTypes = baseTypes;
        }

        public string Namespace { get; }
        public string TypeName { get; }
        public List<ITypeSymbol> BaseTypes { get; }
    }
}
