using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Diagnostics;
using PySharp.SourceGeneration.Utility;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration;

[Generator]
public class PyExceptionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: PySharpTypes.PyExceptionAttribute,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (generatorContext, _) =>
                {
                    var typeSymbol = (INamedTypeSymbol)generatorContext.TargetSymbol;
                    var attribute = typeSymbol.GetAttribute(PySharpTypes.PyExceptionAttribute)!;

                    var @namespace = typeSymbol.ContainingNamespace.IsGlobalNamespace
                        ? string.Empty
                        : typeSymbol.ContainingNamespace.ToDisplayString();

                    // Extract Bases array from the attribute
                    var baseTypes = new List<ITypeSymbol>();

                    if (attribute.TryGetNamedArgument("Bases", out var value))
                    {
                        var errors = ImmutableArray.CreateBuilder<DiagnosticInfo>();
                        Debug.Assert(value.Kind is TypedConstantKind.Array);
                        if (value.IsNull)
                        {
                            errors.Add(DiagnosticInfo.ArgumentNull(attribute, "Bases"));
                            return DiagnosticOr<PyExceptionInfo>.From(errors);
                        }

                        for (int index = 0; index < value.Values.Length; index++)
                        {
                            var element = value.Values[index];
                            Debug.Assert(element.Kind is TypedConstantKind.Type);

                            if (element.Value is null)
                            {
                                errors.Add(DiagnosticInfo.ArgumentNull(attribute, $"Bases[{index}]"));
                                continue;
                            }

                            baseTypes.Add((ITypeSymbol)element.Value);
                        }

                        if (errors.Count > 0)
                            return DiagnosticOr<PyExceptionInfo>.From(errors);
                    }

                    if (baseTypes.Count is 0)
                    {
                        var compilation = generatorContext.SemanticModel.Compilation;
                        var defaultBase = compilation.GetTypeByMetadataName("PySharp.Modules.Builtins.PyExceptionObjectType");
                        DebugHelper.AssertNotNull(defaultBase);
                        baseTypes.Add(defaultBase);
                    }

                    return DiagnosticOr<PyExceptionInfo>.From(new PyExceptionInfo(@namespace, typeSymbol.Name, baseTypes));
                });

        context.RegisterSourceOutput(provider, (context, value) =>
        {
            if (value.HasDiagnostic)
            {
                context.ReportAll(value.Diagnostics);
                return;
            }

            var info = value.Value;

            var builder = new IndentedStringBuilder();
            builder
                .AppendAutoGeneratedTag()
                .UsingNamespace("System")
                .UsingNamespace("PySharp.Runtime")
                .UsingNamespace("PySharp.Modules.Builtins");

            var basesExpr = string.Join(", ", info.BaseTypes.Select(static t => $"{t.Name}.Shared"));

            builder
                .AppendLine($"namespace {info.Namespace}")
                .EnterBlock()
                    .AppendLine($"partial class {info.TypeName} : IPyException<{info.TypeName}>")
                    .EnterBlock()
                        .AppendLine($"public sealed override IReadOnlyList<PyTypeObject> Bases => [{basesExpr}];")
                    .ExitBlock()
                .ExitBlock();

            context.AddSource($"{info.TypeName}.Exception.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        });
    }

    public class PyExceptionInfo
    {
        internal PyExceptionInfo(string @namespace, string typeName, List<ITypeSymbol> baseTypes)
        {
            Namespace = @namespace;
            TypeName = typeName;
            BaseTypes = baseTypes;
        }

        public string Namespace { get; }
        public string TypeName { get; }
        public List<ITypeSymbol> BaseTypes { get; }
    }
}
