using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PySharp.SourceGeneration;

[Generator]
public class PyTypeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: PySharpTypes.PyTypeAttribute,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (generatorContext, _) =>
                {
                    var typeSymbol = (INamedTypeSymbol)generatorContext.TargetSymbol;
                    var pyTypeAttribute = typeSymbol.GetAttribute(PySharpTypes.PyTypeAttribute);
                    var overridenSlots = new List<string>();

                    foreach (var member in typeSymbol.GetMembers())
                    {
                        if (member is not IMethodSymbol methodSymbol)
                            continue;

                        if (methodSymbol.IsDefined(PySharpTypes.PySlotAttribute, inherit: true))
                            overridenSlots.Add(methodSymbol.Name);
                    }

                    return new PyTypeInfo(typeSymbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : typeSymbol.ContainingNamespace.ToDisplayString(),
                        typeSymbol.Name, overridenSlots, pyTypeAttribute);
                });

        context.RegisterSourceOutput(provider, (spc, pyType) =>
        {
            var builder = new IndentedStringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("using System;");
            builder.AppendLine("using PySharp.Runtime;");

            builder
                .AppendLine($"namespace {pyType.Namespace}")
                .EnterBlock()
                    .AppendLine($"partial class {pyType.Name}")
                    .EnterBlock()
                        .AppendLine($"public override string Name => {pyType.AttributeData.ConstructorArguments[0].ToCSharpString()};")
                        .AppendLine($"public override string DefaultModule => {pyType.AttributeData.GetNamedArgumentLiteralOrDefault("Module", "\"builtins\"")};")

                        .AppendLine("protected override void FillSlots()")
                        .EnterBlock()
                            .ForEach(pyType.Slots, (builder, slot) =>
                            {
                                builder.AppendLine($"FillSlot(PySpecialNames.{slot}, ref Slots.{slot}, {slot});");
                            })
                        .ExitBlock()
                    .ExitBlock()
                .ExitBlock();

            spc.AddSource($"{pyType.Name}.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        });
    }

    public class PyTypeInfo
    {
        public PyTypeInfo(string @namespace, string name, List<string> slots, AttributeData attributeData)
        {
            Namespace = @namespace;
            Name = name;
            Slots = slots;
            AttributeData = attributeData;
        }

        public string Namespace { get;}
        public string Name { get; }
        public List<string> Slots { get; }
        public AttributeData AttributeData { get; }
    }
}

