using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PySharp.SourceGeneration.Diagnostics;
using PySharp.SourceGeneration.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;
using static PySharp.SourceGeneration.PyTypeGenerator;

namespace PySharp.SourceGeneration;

[Generator]
public class PyTypeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var predicate = static (SyntaxNode syntaxNode, CancellationToken _) => syntaxNode is ClassDeclarationSyntax;

        var pyTypeProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: PySharpTypes.PyTypeAttribute,
                predicate: predicate,
                transform: static (generatorContext, ct) => Transform(generatorContext, ct))
            .WhereNotNull();

        var pyExceptionProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: PySharpTypes.PyExceptionAttribute,
                predicate: predicate,
                transform: static (generatorContext, ct) => Transform(generatorContext, ct))
            .WhereNotNull();

        var combined = pyTypeProvider.Collect().Combine(pyExceptionProvider.Collect())
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right));

        context.RegisterSourceOutput(combined, (spc, pyTypes) =>
        {
            foreach (var pyType in pyTypes)
                GenerateSource(spc, pyType);
        });
    }

    private static DiagnosticOr<PyTypeInfo>? Transform(GeneratorAttributeSyntaxContext generatorContext, CancellationToken _)
    {
        var typeSymbol = (INamedTypeSymbol)generatorContext.TargetSymbol;

        var pyTypeAttribute = typeSymbol.GetAttribute(PySharpTypes.PyTypeAttribute)
                              ?? typeSymbol.GetAttribute(PySharpTypes.PyExceptionAttribute)!;

        // The qual name is required for the whole type; an explicitly null value makes the type invalid,
        // an undecodable constant (e.g. a name generated by another generator) falls back to an empty name.
        if (!pyTypeAttribute.TryGetRequiredStringArgument(0, "qualName", out var qualName, out var qualNameError))
        {
            if (qualNameError is not null)
                return DiagnosticOr<PyTypeInfo>.From(qualNameError);
            return null;
        }

        var pyTypeConstructorAttribute = typeSymbol.GetAttribute(PySharpTypes.PyTypeConstructorAttribute, inherit: true);
        bool doNotGenerateConstructor = false;
        string accessModifier = "private";
        if (pyTypeConstructorAttribute is not null)
        {
            doNotGenerateConstructor = pyTypeConstructorAttribute.GetNamedArgumentOrDefault("DoNotGenerateConstructor", false);
            accessModifier = pyTypeConstructorAttribute.GetNamedArgumentOrDefault("AccessModifier", "private")!;
        }

        var @namespace = typeSymbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : typeSymbol.ContainingNamespace.ToDisplayString();
        var pyTypeInfo = new PyTypeInfo(@namespace, typeSymbol.Name, pyTypeAttribute, doNotGenerateConstructor, accessModifier, qualName);

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member is not IMethodSymbol methodSymbol)
                continue;

            if (methodSymbol.IsDefined(PySharpTypes.PySlotAttribute, inherit: true))
            {
                var slotAttr = methodSymbol.GetAttributes(PySharpTypes.PySlotAttribute, inherit: true).Single();
                var slotsMember = slotAttr.GetNamedArgumentOrDefault<string?>("SlotsMember", null);
                pyTypeInfo.Slots.Add(new(methodSymbol.Name, slotsMember));
            }

            void Collect(AttributeData attribute, List<DiagnosticOr<PyMethodInfo>> infos)
            {
                if (attribute.TryGetRequiredStringArgument(0, "name", out var methodName, out var methodNameError))
                    infos.Add(DiagnosticOr<PyMethodInfo>.From(new PyMethodInfo(methodSymbol.Name, SymbolDisplay.FormatPrimitive(methodName, quoteStrings: true, useHexadecimalNumbers: false)!, attribute.GetNamedArgumentOrDefault("Order", 1))));
                else if (methodNameError is not null)
                    infos.Add(DiagnosticOr<PyMethodInfo>.From(methodNameError));
            }

            var methodAttribute = methodSymbol.GetAttribute(PySharpTypes.PyMethodAttribute);
            if (methodAttribute is not null)
                Collect(methodAttribute, pyTypeInfo.Methods);

            var classMethodAttribute = methodSymbol.GetAttribute(PySharpTypes.PyClassMethodAttribute);
            if (classMethodAttribute is not null)
                Collect(classMethodAttribute, pyTypeInfo.ClassMethods);

            var staticMethodAttribute = methodSymbol.GetAttribute(PySharpTypes.PyStaticMethodAttribute);
            if (staticMethodAttribute is not null)
                Collect(staticMethodAttribute, pyTypeInfo.StaticMethods);

            var propertyAttribute = methodSymbol.GetAttribute(PySharpTypes.PyPropertyAttribute);
            if (propertyAttribute is not null)
            {
                if (!propertyAttribute.TryGetRequiredStringArgument(0, "name", out var propertyName, out var propertyNameError))
                {
                    if (propertyNameError is not null)
                        pyTypeInfo.Properties.Add(DiagnosticOr<PyPropertyInfo>.From(propertyNameError));
                    // Undecodable name: skip this property accessor silently.
                }
                else
                {
                    var nameLiteral = SymbolDisplay.FormatPrimitive(propertyName, quoteStrings: true, useHexadecimalNumbers: false)!;

                    var methodType = propertyAttribute.GetNamedArgumentOrDefault("Type", 0);
                    if (methodType < 0 || methodType > 2)
                    {
                        var info = DiagnosticInfo.InvalidEnumValue(propertyAttribute, "Type", methodType, "PyPropertyMethodType");
                        pyTypeInfo.Properties.Add(DiagnosticOr<PyPropertyInfo>.From(info));
                    }
                    else
                    {
                        var info = new PyPropertyInfo(nameLiteral);
                        if (methodType is 0)
                            info.Getter = methodSymbol.Name;
                        else if (methodType is 1)
                            info.Setter = methodSymbol.Name;
                        else if (methodType is 2)
                            info.Deleter = methodSymbol.Name;
                        pyTypeInfo.Properties.Add(DiagnosticOr<PyPropertyInfo>.From(info));
                    }
                }
            }
        }

        return DiagnosticOr<PyTypeInfo>.From(pyTypeInfo);
    }

    private static void GenerateSource(SourceProductionContext context, DiagnosticOr<PyTypeInfo> result)
    {
        // Report the whole-type error (invalid qual name) and skip generation.
        if (result.HasDiagnostic)
        {
            context.ReportAll(result.Diagnostics);
            return;
        }

        var pyType = result.Value;

        // Report member-level errors and keep only the valid methods/properties.
        var methods = CollectValid(pyType.Methods, context);
        var classMethods = CollectValid(pyType.ClassMethods, context);
        var staticMethods = CollectValid(pyType.StaticMethods, context);

        var properties = new Dictionary<string, PyPropertyInfo>();
        foreach (var p in pyType.Properties)
        {
            if (p.HasDiagnostic)
            {
                context.ReportAll(p.Diagnostics);
                continue;
            }

            // Group accessors (getter/setter/deleter) by their Python property name.
            var accessor = p.Value;
            if (!properties.TryGetValue(accessor.NameLiteral, out var group))
                properties[accessor.NameLiteral] = group = new PyPropertyInfo();

            if (accessor.Getter is not null)
                group.Getter = accessor.Getter;
            else if (accessor.Setter is not null)
                group.Setter = accessor.Setter;
            else if (accessor.Deleter is not null)
                group.Deleter = accessor.Deleter;
        }

        var builder = new IndentedStringBuilder();
        builder
            .AppendAutoGeneratedTag()
            .UsingNamespace("System")
            .UsingNamespace("PySharp.Runtime")
            .UsingNamespace("PySharp.Modules.Builtins");

        var qualName = pyType.QualNameLiteral;
        var name = pyType.QualName is not null
            ? SymbolDisplay.FormatPrimitive(pyType.QualName.Split('.').Last(), quoteStrings: true, useHexadecimalNumbers: false)
            : "\"\"";

        builder
            .AppendLine($"namespace {pyType.Namespace}")
            .EnterBlock()
                .AppendLine($"partial class {pyType.Name}")
                .EnterBlock()
                    .AppendLine($"protected override string DefaultName => {name};")
                    .AppendLine($"protected override string DefaultQualName => {qualName};")
                    .AppendLine($"protected override string DefaultModule => {pyType.AttributeData.GetNamedArgumentLiteralOrDefault("Module", "\"builtins\"")};")
                    .AppendLine($"public override bool IsSealed => {pyType.AttributeData.GetNamedArgumentLiteralOrDefault("IsSealed", "false")};")
                    .If(!pyType.DoNotGenerateConstructor, builder =>
                    {
                        builder
                            .AppendLine($"{pyType.AccessModifier} {pyType.Name}()")
                            .EnterBlock()
                            .ExitBlock()
                            .AppendLine($"public static {pyType.Name} Shared {{ get; }} = new {pyType.Name}();");
                    })
                    .If(pyType.Slots.Count > 0, builder => builder
                        .AppendLine("protected override void FillSlots()")
                        .EnterBlock()
                            .ForEach(pyType.Slots, static (builder, slot) =>
                            {
                                if (slot.Name is "New")
                                    builder.AppendLine("FillNewSlot();");
                                else if (slot.SlotsMember is not null)
                                    builder.AppendLine($"FillSlot(PySpecialNames.{slot.Name}, ref Slots.{slot.SlotsMember}.{slot.Name}, {slot.Name});");
                                else
                                    builder.AppendLine($"FillSlot(PySpecialNames.{slot.Name}, ref Slots.{slot.Name}, {slot.Name});");
                            })
                        .ExitBlock())

                    .If(methods.Count > 0 || classMethods.Count > 0 || staticMethods.Count > 0, builder => builder
                        .AppendLine("protected override void RegisterMethods()")
                        .EnterBlock()
                            .ForEach(methods.GroupBy(static info => info.PyNameLiteral), static (builder, impls) =>
                            {
                                builder.AppendLine($"AppendMethodDescriptor({impls.Key}, {string.Join(", ", impls.OrderBy(static info => info.Order).Select(static info => info.Name))});");
                            })
                            .ForEach(classMethods.GroupBy(static info => info.PyNameLiteral), static (builder, impls) =>
                            {
                                builder.AppendLine($"AppendClassMethod({impls.Key}, {string.Join(", ", impls.OrderBy(static info => info.Order).Select(static info => info.Name))});");
                            })
                            .ForEach(staticMethods.GroupBy(static info => info.PyNameLiteral), static (builder, impls) =>
                            {
                                builder.AppendLine($"AppendStaticMethod({impls.Key}, {string.Join(", ", impls.OrderBy(static info => info.Order).Select(static info => info.Name))});");
                            })
                        .ExitBlock())

                    .If(properties.Count > 0, builder => builder
                        .AppendLine("protected override void RegisterProperties()")
                        .EnterBlock()
                            .ForEach(properties, static (builder, pair) =>
                            {
                                builder.AppendLine($"AppendMemberDescriptor({pair.Key}, {pair.Value.Getter ?? "null"}, {pair.Value.Setter ?? "null"}, {pair.Value.Deleter ?? "null"});");
                            })
                        .ExitBlock())

                .ExitBlock()
            .ExitBlock();

        context.AddSource($"{pyType.Name}.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Reports the diagnostics of the given member results and returns only the valid ones.
    /// </summary>
    private static List<PyMethodInfo> CollectValid(List<DiagnosticOr<PyMethodInfo>> results, SourceProductionContext context)
    {
        var valid = new List<PyMethodInfo>(results.Count);

        foreach (var result in results)
        {
            if (result.HasDiagnostic)
                context.ReportAll(result.Diagnostics);
            else
                valid.Add(result.Value);
        }

        return valid;
    }

    public class PyTypeInfo
    {
        public PyTypeInfo(string @namespace, string name, AttributeData attributeData, bool doNotGenerateConstructor, string accessModifier, string qualName)
        {
            Namespace = @namespace;
            Name = name;
            Slots = [];
            AttributeData = attributeData;
            DoNotGenerateConstructor = doNotGenerateConstructor;
            AccessModifier = accessModifier;
            Methods = [];
            ClassMethods = [];
            StaticMethods = [];
            Properties = [];
            QualName = qualName;
        }

        public string Namespace { get; }
        public string Name { get; }
        public List<PySlotInfo> Slots { get; }
        internal List<DiagnosticOr<PyMethodInfo>> Methods { get; }
        internal List<DiagnosticOr<PyMethodInfo>> ClassMethods { get; }
        internal List<DiagnosticOr<PyMethodInfo>> StaticMethods { get; }
        internal List<DiagnosticOr<PyPropertyInfo>> Properties { get; }
        public AttributeData AttributeData { get; }
        public bool DoNotGenerateConstructor { get; }
        public string AccessModifier { get; }
        public string QualNameLiteral => SymbolDisplay.FormatPrimitive(QualName, quoteStrings: true, useHexadecimalNumbers: false)!;
        public string QualName { get; }
    }

    public record class PySlotInfo
    {
        public PySlotInfo(string name, string? slotsMember)
        {
            Name = name;
            SlotsMember = slotsMember;
        }

        public string Name { get; }
        public string? SlotsMember { get; }
    }

    public record class PyMethodInfo
    {
        public PyMethodInfo(string name, string pyNameLiteral, int order)
        {
            Name = name;
            PyNameLiteral = pyNameLiteral;
            Order = order;
        }

        public string Name { get; }
        public string PyNameLiteral { get; }
        public int Order { get; }
    }

    public record class PyPropertyInfo
    {
        public PyPropertyInfo()
        {
        }

        public PyPropertyInfo(string nameLiteral)
        {
            NameLiteral = nameLiteral;
        }

        /// <summary>The Python property name (C# literal) used to group accessors.</summary>
        public string NameLiteral { get; } = "";

        public string? Getter { get; set; }
        public string? Setter { get; set; }
        public string? Deleter { get; set; }
    }
}


