namespace PySharp.Tokenization;

public enum TokenType
{
    None = 0,

    EndMarker = None,
    Name,
    Number,
    String,
    NewLine,
    Indent,
    Dedent,
    LeftParen,
    RightParen,
    LeftSquareBracket,
    RightSquareBracket,
    Colon,
    Comma,
    Semicolon,
    Plus,
    Minus,
    Star,
    Slash,
    Pipe,
    Ampersand,
    Less,
    Greater,
    Equal,
    Dot,
    Percent,
    LeftBrace,
    RightBrace,
    DoubleEqual,
    NotEqual,
    LessEqual,
    GreaterEqual,
    Tilde,
    Caret,
    LeftShift,
    RightShift,
    DoubleStar,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    PercentEqual,
    AmpersandEqual,
    PipeEqual,
    CaretEqual,
    LeftShiftEqual,
    RightShiftEqual,
    DoubleStarEqual,
    DoubleSlash,
    DoubleSlashEqual,
    At,
    AtEqual,
    RightArrow,
    Ellipsis,
    ColonEqual,
    Exclamation,
    Operator,
    TypeIgnore,
    TypeComment,
    SoftKeyword,
    FStringStart,
    FStringMiddle,
    FStringEnd,
    Comment,
    NL,
    ErrorToken,
    Encoding,

    Count,
}